<a href="https://colab.research.google.com/github/va4756/yemoon_bigdata_test/blob/main/bigdata_%EC%98%88%EB%AC%B8_%EC%8B%A4%EC%A0%84%EB%AC%B8%EC%A0%9C_example2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01. 2회 기출문제

## 데이터 동기화

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
!git clone https://github.com/AnalyticsKnight/yemoonsaBigdata/

fatal: destination path 'yemoonsaBigdata' already exists and is not an empty directory.

## 제 1유형 문제

### 문1-1) Boston Housing 데이터셋에서
-  상위 10번째 값으로 상위 10개의 값을 변환하고
- age가 80이상인 데이터를 추출하고
- crim의 평균값 계산

In [15]:
# 데이터 불러오기
import pandas as pd
df = pd.read_csv("/content/yemoonsaBigdata/datasets/Part5/201_boston.csv")
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

In [16]:
# 내림차순으로 정렬(CRIM)
df = df.sort_values(by='CRIM', ascending=False)
df.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
380,88.9762,0.0,18.1,0.0,0.671,6.968,91.9,1.4165,24.0,666.0,20.2,396.90,17.21
418,73.5341,0.0,18.1,0.0,0.679,5.957,100.0,1.8026,24.0,666.0,20.2,16.45,20.62
405,67.9208,0.0,18.1,0.0,0.693,5.683,100.0,1.4254,24.0,666.0,20.2,384.97,22.98
410,51.1358,0.0,18.1,0.0,0.597,5.757,100.0,1.4130,24.0,666.0,20.2,2.60,10.11
414,45.7461,0.0,18.1,0.0,0.693,4.519,100.0,1.6582,24.0,666.0,20.2,88.27,36.98
404,41.5292,0.0,18.1,0.0,0.693,5.531,85.4,1.6074,24.0,666.0,20.2,329.46,27.38
398,38.3518,0.0,18.1,0.0,0.693,5.453,100.0,1.4896,24.0,666.0,20.2,396.90,30.59
427,37.6619,0.0,18.1,0.0,0.679,6.202,78.7,1.8629,24.0,666.0,20.2,18.82,14.52
413,28.6558,0.0,18.1,0.0,0.597,5.155,100.0,1.5894,24.0,666.0,20.2,210.97,20.08
417,25.9406,0.0,18.1,0.0,0.679,5.304,89.1,1.6475,24.0,666.0,20.2,127.36,26.64

In [17]:
# 특정 위치 데이터 찾기(CRIM의 10번째 값)
crim_val = df.iloc[9, 0]  # [10번째 행, 1번째 열] = [9, 0]
crim_val

25.9406

In [19]:
# 특정 위치 데이터 변경하기
df.iloc[:10, 0] = crim_val
df.head(11)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
380,25.9406,0.0,18.1,0.0,0.671,6.968,91.9,1.4165,24.0,666.0,20.2,396.90,17.21
418,25.9406,0.0,18.1,0.0,0.679,5.957,100.0,1.8026,24.0,666.0,20.2,16.45,20.62
405,25.9406,0.0,18.1,0.0,0.693,5.683,100.0,1.4254,24.0,666.0,20.2,384.97,22.98
410,25.9406,0.0,18.1,0.0,0.597,5.757,100.0,1.4130,24.0,666.0,20.2,2.60,10.11
414,25.9406,0.0,18.1,0.0,0.693,4.519,100.0,1.6582,24.0,666.0,20.2,88.27,36.98
404,25.9406,0.0,18.1,0.0,0.693,5.531,85.4,1.6074,24.0,666.0,20.2,329.46,27.38
398,25.9406,0.0,18.1,0.0,0.693,5.453,100.0,1.4896,24.0,666.0,20.2,396.90,30.59
427,25.9406,0.0,18.1,0.0,0.679,6.202,78.7,1.8629,24.0,666.0,20.2,18.82,14.52
413,25.9406,0.0,18.1,0.0,0.597,5.155,100.0,1.5894,24.0,666.0,20.2,210.97,20.08
417,25.9406,0.0,18.1,0.0,0.679,5.304,89.1,1.6475,24.0,666.0,20.2,127.36,26.64
400,25.0461,0.0,18.1,0.0,0.693,5.987,100.0,1.5888,24.0,666.0,20.2,396.90,26.77

In [22]:
# 조건부 평균 계산하기  # 소수 셋째자리까지
cond = df[df['AGE'] >= 80]
result = cond['CRIM'].mean()
print(round(result, 3))

5.759

### 문1-2) Californai Housing 데이터셋에서
- 순서대로 80%의 데이터를 추출하고
- 'total_bedrooms' 변수의 중앙값을 구하고
- 'total_bedrooms'의 결측치에 이 값으로 대체한 후,
- 결측치 대체 전과 후의 표준편차를 구하고
- 이 둘의 차를 절대값으로 구하시오.

In [23]:
import pandas as pd

df = pd.read_csv("/content/yemoonsaBigdata/datasets/Part5/202_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [25]:
# 데이터 추출하기
val_80 = int(len(df) * 0.8)
rst_df = df.iloc[:val_80]['total_bedrooms']
rst_df

0         129.0
1        1106.0
2         190.0
3         235.0
4         280.0
          ...
16507     599.0
16508     331.0
16509     411.0
16510     941.0
16511     417.0
Name: total_bedrooms, Length: 16512, dtype: float64

In [26]:
# 표준편차, 중앙값 계산하기
rst_std = rst_df.std()
rst_med = rst_df.median()
rst_std, rst_med

(435.900577052527, 436.0)

In [27]:
# 결측값 채우기 & 표준편차 계산하기
rst_df_fillna = rst_df.fillna(rst_med)
rst_std_2 = rst_df_fillna.std()
rst_std_2

433.9254297608813

In [28]:
# 결과 출력하기
result = abs(rst_std - rst_std_2)
result

1.975147291645726

### 문1-3) (문1-2)의 Californai Housing 데이터셋에서
- 'population' 컬럼에서 이상치의 갯수를 구하시오
- 이상치를 구하기 위해서는 평균, 1.5X(표준편차) 를 이용한다.

In [30]:
import pandas as pd

df = pd.read_csv("/content/yemoonsaBigdata/datasets/Part5/202_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [34]:
# 이상치 -> 여기서는 평균과 표준편차를 구한다
mean_p = df['population'].mean()
std_p = df['population'].std()
cond1 = df['population'] < (mean_p - 1.5 * std_p )
cond2 = df['population'] > (mean_p + 1.5 * std_p )
result= df['population'](cond1 | cond2)
result.sum()

TypeError: 'Series' object is not callable