<a href="https://colab.research.google.com/github/va4756/yemoon_bigdata_test/blob/main/bigdata_%EC%8B%9C%EB%82%98%EA%B3%B5_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Jupyter Notebook에서 /Google 드라이브/2025_시나공_빅데이터분석기사_실기_데이터파일/ -> 에 있음

## Section1.(p148)

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1qw0gzFa8RuC6eEN0cZFi3CCbVW-sp3NXddF_gMCer4M#gid=0

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
print(df.shape)
df.head()

(120, 10)

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

### 01.필터링, 최소값, 중앙값

In [ ]:
# 0 제외
cond = (df['f5'] != 0)
df[cond]
print(df.shape)

(120, 10)

In [ ]:
# 'views' 컬럼 결측치 최소값으로 채우기
print(df['views'].isnull().sum())
min = df['views'].min(skipna=True)
df['views'].fillna(min, inplace=True)

# 'views' 컬럼 중앙값 계산
print(int(df['views'].median()))

4
5924

<ipython-input-20-8490c3110aa2>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['views'].fillna(min, inplace=True)

### 02.카테고리, 인덱스, 문자열 슬라이싱(p149)

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
# subscribed 종류 중 가장 많은 날짜 구하기
df = df['subscribed'].value_counts()
print(df.head())
# 일(day)값을 찾고, 정수형으로 변경
int(df.index[0][-2:])

subscribed
2025-02-17    16
2024-06-21     3
2024-04-03     2
2024-07-29     2
2024-05-28     2
Name: count, dtype: int64

17

### 03.파생변수, 정렬, 인덱싱(p150)

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
# 결측치 제거
df = df.dropna()
print(df.isnull().sum().sum())

# 새로운 컬럼 계산
df['new'] = df['views'] / df['f1']

# 내림차순 정렬
df = df.sort_values(by='new', ascending=False)

# age 값 찾아서 출력
result = int(df.iloc[0, 1])    # iloc[행, 열]
result

0

22

### 04.값 변경, 정렬, 합계(p151)

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
# 결측 데이터 0으로 대체
df['views'].fillna(0, inplace=True)   # 할당하지 말 것
print(df.head())

# 내림차순 정렬
df = df.sort_values(by='views', ascending=False)

# views 상위 10개 데이터에 최소값 대입
views_min = df.iloc[:10]['views'].min()
df.loc[:10, 'views'] = views_min

# views 컬럼의 합
result = int(df['views'].sum())
print('*'*50)
print(result)

        id   age city    f1  f2   f3    f4         f5  subscribed   views
5     id06  22.0   서울  57.0   0  vip  INTP  20.129444  2024-09-12  9877.0
56    id56  59.0   대구   NaN   1  vip  ESTJ  73.586397  2024-04-05  9877.0
83    id83  73.0   경기  50.0   1  vip  ENTP  80.138280  2024-09-26  9877.0
32    id32  25.0   부산  64.0   0  vip  ISFJ  13.049921  2024-05-24  9877.0
100  id100  47.0   경기  53.0   0  vip  ESFP  33.308999  2024-02-21  9877.0
**************************************************
652812

<ipython-input-43-0fc2bb8142cc>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['views'].fillna(0, inplace=True)

### 05.문자열 슬라이싱, 파생변수, 평균값(p152)

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
# f4 컬럼에서 뒤에 2개 값 슬라이싱
# df['new'] = df['f4'].str[2:4]
cond = df['f4'].str.contains('FJ')

# FJ인 데이터 찾기
# cond = (df['new'] == 'FJ')
df = df[cond]
print(df[cond].head())

# f2 평균 구하기
print('*'*50)
print(round(df['f2'].mean(), 2))

     id   age city     f1  f2      f3    f4         f5  subscribed   views
0  id01   2.0   서울    NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울   70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
4  id05  24.0   서울   85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
6  id07  36.3   서울   60.0   1     NaN  ISFJ   9.796378  2024-01-11    61.0
7  id08  38.0   서울  101.0   1  silver  INFJ  83.685380  2024-03-06  3260.0
**************************************************
0.61

<ipython-input-15-7ac6b9ceafd8>:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(df[cond].head())

### 06.필터링, 분산(p154)

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
# 조건에 맞는 데이터
cond1 = df['f3'] == 'gold'
cond2 = df['f2'] == 2
df = df[cond1 & cond2]

# 분산
result = df['f1'].var()

# 출력
print(round(result, 2))

235.43

### 07.값 변경(연산), 필터링 절댓값

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
# 나이 + 1
df['age'] = df['age'] + 1

# 20대, 30대 조건
cond1 = (df['age'] >= 20) & (df['age'] < 30)
cond2 = (df['age'] >= 30) & (df['age'] < 40)

# 20대와 30대 views 평균의 차이(절대값)
diff = abs(df[cond1]['views'].mean() - df[cond2]['views'].mean())
print(round(diff, 2))

263.13

### 08.시계열 데이터, 필터링, 데이터 개수

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
# 자료형 변환
df['subscribed'] = pd.to_datetime(df['subscribed'])

# 파생변수 생성 (년, 월)
df['year'] = df['subscribed'].dt.year
df['month'] = df['subscribed'].dt.month

# 2024년 2월이고, 'f3'이 gold인 데이터
cond1 = df['year'] == 2024
cond2 = df['month'] == 2
cond3 = df['f3'] == 'gold'
df = df[cond1 & cond2 & cond3]

# 데이터 개수
print(df)
print('*'*50)
print(len(df))

      id   age city    f1  f2    f3    f4         f5 subscribed   views  year  \
22  id22  -6.3   부산  72.0   1  gold  ENFP  52.667078 2024-02-09  6147.0  2024
31  id31  86.0   부산  77.0   0  gold  ESFJ  73.586397 2024-02-11  8014.0  2024
42  id42  65.0   대구  48.0   2  gold  ESTP  33.308999 2024-02-09  5999.0  2024
55  id55  75.0   대구  63.0   2  gold  ENTP  13.049921 2024-02-06  6042.0  2024
64  id64  43.0   경기  62.0   2  gold  ESFP  73.586397 2024-02-22  5995.0  2024

    month
22      2
31      2
42      2
55      2
64      2
**************************************************
5

### 09.필터링, 카테고리, 최빈값(p157)

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
# df.info()

In [ ]:
# views수가 1000이하
cond = df['views'] <= 1000
df = df[cond]

# f4컬럼 종류별 개수
df = df['f4'].value_counts()

# f4컬럼 최빈값
print(df.index[0])

ISFJ

### 10.그룹핑, 최댓값, 정렬(p158)

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
# 결측치가 있는 행은 삭제하고
df.dropna(inplace=True)   # 값을 할당하지 않는다.

# 지역별 평균 계산
df = df.groupby(['city']).mean(numeric_only=True)

# 'f2'컬럼이 가장 큰 지역 출력
# print(df.sort_values('f2', ascending=False).index[0])
print(df['f2'].idxmax())

서울

### 11.슬라이싱, 사분위수, 결측치 제거(p160)

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
# 결측치가 있는 행 제거
df.dropna(inplace=True)

# 70% 지점
end = int(len(df) * 0.7)

# 70% 데이터 슬라이싱
df = df.iloc[:end]

# 3사분위수, 1사분위수
q3 = df['views'].quantile(0.75)
q1 = df['views'].quantile(0.25)

# 결과 출력
print(int(q3 - q1))

2771

### 12.결측치 처리, 최빈값, 데이터 개수(p161)

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
# 결측치가 가장 많은 컬럼, 출력 결과로 확인
print(df.isnull().sum())
df['f3'].value_counts()

id             0
age            0
city           0
f1            31
f2             0
f3            29
f4             0
f5             0
subscribed     0
views          4
dtype: int64

f3
gold      57
silver    22
vip       12
Name: count, dtype: int64

In [ ]:
# 결측치가 가장 많은 컬럼 제거
df = df.dropna(subset=['f1'])

# 두번째로 가장 결측치가 많은 컬럼 최빈값 대체
freq = df['f3'].mode()[0]
df['f3'].fillna(freq, inplace=True)

# f3컬럼이 gold인 데이터의 수
print(sum(df['f3'] == 'gold'))

63

<ipython-input-21-4eeb61e728a9>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['f3'].fillna(freq, inplace=True)
<ipython-input-21-4eeb61e728a9>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['f3'].fillna(freq, inplace=True)

In [ ]:
# 방법2
# 결측치가 가장 많은 컬럼
col = df.isnull().sum().idxmax()

# 결측치가 가장 많은 컬럼 제거
df = df.dropna(subset=[col])

# 두번째로 가장 결측치가 많은 컬럼 최빈값 대체
freq = df['f3'].mode()[0]
df['f3'] = df['f3'].fillna(freq)

# f3컬럼이 gold인 데이터의 수
print(len(df[df['f3'] == 'gold']))

61

<ipython-input-22-cba827c99d83>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['f3'] = df['f3'].fillna(freq)

### 13.결측 데이터 찾기, 필터링, 평균값(p163)

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
# 결측치가 있는 데이터 True / False
cond = df['f1'].isnull()

# 결측치가 있는 데이터 선택
df = df[cond]

# age의 평균값을 구하시오
print(round(df['age'].mean(), 1))

53.6

### 14.중복데이터 제거, 값 변경, 데이터 개수(p164)

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          118 non-null    object
 1   age         118 non-null    float64
 2   city        118 non-null    object
 3   f1          87 non-null     float64
 4   f2          118 non-null    int64
 5   f3          89 non-null     object
 6   f4          118 non-null    object
 7   f5          118 non-null    float64
 8   subscribed  118 non-null    object
 9   views       114 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 10.1+ KB

In [ ]:
import numpy as np

# 중복데이터 제거
df.drop_duplicates(inplace=True)

# 값 대체
print(df['f3'].value_counts())
df['f3'] = df['f3'].replace(np.nan, 0).replace('silver', 1).replace('gold', 2).replace('vip', 3)

# f3컬럼의 총합 (정수형으로 출력)
print(int(df['f3'].sum()))

f3
gold      56
silver    22
vip       11
Name: count, dtype: int64
167

<ipython-input-4-2d7711655b8b>:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['f3'] = df['f3'].replace(np.nan, 0).replace('silver', 1).replace('gold', 2).replace('vip', 3)

In [ ]:
# map 을 사용하는 방법
import numpy as np

# 중복데이터 제거
df.drop_duplicates(inplace=True)

# 값 대체
df['f3'].value_counts()

# map()을 사용한 값 대체
mapping = {np.nan: 0, 'silver': 1, 'gold':2, 'vip':3}
df['f3'].map(mapping).fillna(0).astype(int)

print(int(df['f3'].sum()))

167

### 15.컬럼 삭제, 행 단위 합계, 필터링(p166)

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    object
 1   age         120 non-null    float64
 2   city        120 non-null    object
 3   f1          89 non-null     float64
 4   f2          120 non-null    int64
 5   f3          91 non-null     object
 6   f4          120 non-null    object
 7   f5          120 non-null    float64
 8   subscribed  120 non-null    object
 9   views       116 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 9.5+ KB

In [ ]:
# 자료형이 object 컬럼 선택
cols = df.select_dtypes(exclude='object').columns
df = df[cols]
print(df.info())

# 결측치 0으로 대체
df = df.fillna(0)

# 행과 열 변경
df = df.T

# 행별 합이 3000이상인 데이터 수
print('*'*50)
print(sum(df.sum() > 3000))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     120 non-null    float64
 1   f1      89 non-null     float64
 2   f2      120 non-null    int64
 3   f5      120 non-null    float64
 4   views   116 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 4.8 KB
None
**************************************************
88

### 16.이상치, IQR(p167)

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
# 3사분위 1사분위
q1 = df['views'].quantile(0.25)
q3 = df['views'].quantile(0.75)

# IQR 계산
IQR = q3 - q1

# 이상치 기준 찾기
lower_bound = q1 - 1.5 * IQR
upper_bound = q3 + 1.5 * IQR

# 이상치 조건에 만족하는 데이터 찾기
cond1 = df['views'] < lower_bound
cond2 = df['views'] > upper_bound
df = df[cond1 | cond2]

# 이상치 데이터의 views 컬럼 합
print(int(df['views'].sum()))

77699

### 17.이상치, 소수점 있는 데이터 찾기, 표준편차(p168)

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
# 표준편차
view_std_1 = df['views'].std()
print(view_std_1)

# 음수이거나 0인 테이터 제외(age)
cond = df['age'] <= 0
df = df[~cond]

# 소수점이 없는 값만 선택
cond = df['age'] == round(df['age'], 0)
df = df[cond]

# 표준편차
view_std_2= df['views'].std()

print(round((view_std_1 + view_std_2), 2))

4121.626455600414
8297.31

### 18.데이터(행) 기준 평균값, 인덱싱(p169)

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data2.csv", index_col="year")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data2.csv", index_col="year")
df.head()

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
year,,,,,,,,,,,,,,,,,,,,,
2000,137,74,114,140,80,150,16,133,178,181,...,124,94,118,12,50,191,137,174,56,128
2001,176,87,64,110,128,16,8,4,123,87,...,59,22,3,108,17,104,101,161,156,43
2002,128,132,123,112,134,160,180,47,115,155,...,160,111,116,75,48,51,81,101,194,73
2003,78,45,26,50,177,119,47,72,163,125,...,163,88,52,79,192,83,5,75,196,119
2004,1,162,124,12,1,126,58,123,186,161,...,100,93,86,12,115,72,29,30,88,150

In [ ]:
# 2001에서, 평균보다 큰값 합계
# (참고) sum()은 판다스에서는 기본적으로 컬럼별 계산을 한다.
m1 = df.loc[2001].mean()
cond1 = df.loc[2001] > m1
r1 = sum(cond1)
print(r1)

# 2003에서, 평균보다 작은값 합계
m2 = df.loc[2003].mean()
cond2 = df.loc[2003] < m2
r2 = sum(cond2)
print(r2)
print('*' * 50)
print(r1 + r2)

100
102
**************************************************
202

In [ ]:
# loc를 사용하기 싫으면 T를 사용할 것
df = df.T

m1 = df[2001].mean()
cond1 = df[2001] > m1
r1 = sum(cond1)

m2 = df[2003].mean()
cond2 = df[2003] < m2
r2 = sum(cond2)

print(r1 + r2)

202

### 19.결측치(뒤의 값으로 대체), 그룹합(p171)

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
# 결측치 채우기
df = df.fillna(method='bfill')

# city와 f2기준 그룹합 계산
df = df.groupby(['city', 'f2']).sum(numeric_only=True).reset_index()
print(df.head())

# 내림차순 정렬
df = df.sort_values('views', ascending=False)

# 3번째로 큰 값 출력
print(df.iloc[2, 0])

  city  f2     age      f1           f5     views
0   경기   0  1192.9  1490.0  1425.236647  154066.0
1   경기   1   997.0  1016.0   935.958628   91442.0
2   경기   2   296.0   390.0   430.186433   42709.0
3   대구   0   664.0   982.0   371.184620  100421.0
4   대구   1   393.6   471.0   404.779978   49536.0
경기

<ipython-input-51-2e6541940577>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='bfill')

### 20.시계열 데이터, 월별 집계, 인덱스(p172)

In [ ]:
import pandas as pd
# df = pd.read_csv("type1_data1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/type1_data1.csv")
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [ ]:
# 자료형 변환
df['subscribed'] = pd.to_datetime(df['subscribed'])

# 파생변수 생성
df['month'] = df['subscribed'].dt.month

# 월별로 데이터 합 집계
df = df.groupby('month').sum(numeric_only=True)
print(df.head())

# 오름차순 정렬 및 가장 작은값 출력
print('*'*50)
print(df.sort_values('views').index[0])

         age      f1  f2          f5     views
month
1      441.8   608.0   1  487.453162   40013.0
2      860.7  1301.0  25  460.248156  165852.0
3      326.3   457.0   8  352.729057   39031.0
4      307.0   268.0   4  312.187975   41307.0
5      809.6   822.0  10  855.287894  110786.0
**************************************************
11

### 21.시간 간의 차이 계산(분), 필터링(p173)

In [ ]:
import pandas as pd
# df = pd.read_csv("delivery_time.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/delivery_time.csv")
df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

In [ ]:
# datetime으로 자료형 변경
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'])
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'])

# 지연시간 계산(분)
df['지연시간'] = (df['실제도착시간'] - df['예상도착시간']).dt.total_seconds() / 60

# 조건1 - 예상 도착시간보다 늦게 도착한 건
cond1 = df['지연시간'] > 0

# 조건2 - 거리가 7 이상인 건
cond2 = df['거리'] >= 7

# 조건에 맞는 데이터(행) 수 출력
print(len(df[cond1 & cond2]))

311

### 22.시간 간의 차이 계산(분), 그룹핑(p174)

In [ ]:
import pandas as pd
# df = pd.read_csv("delivery_time.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/delivery_time.csv")
df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

In [ ]:
# datetime으로 자료형 변경
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'])
df['주문시간'] = pd.to_datetime(df['주문시간'])

# 실제 도착시간과 주문시간 차이 계산(분)
df['diff'] = (df['실제도착시간'] - df['주문시간']).dt.total_seconds() / 60

# 앱종류별 도착시간과 주문시간 차이의 평균 계산
df = df.groupby('앱종류')['diff'].mean()

# 가장 작은 시간(분) 반올림 후 출력
print(round(df.min()))

62

### 23.시간 간의 차이 계산(분), 비율(p175)

In [ ]:
import pandas as pd
# df = pd.read_csv("delivery_time.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/delivery_time.csv")
df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

In [ ]:
# datetime 자료형으로 변경
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'])
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'])

# 지연시간 계산(분)
df['지연시간'] = (df['실제도착시간'] - df['예상도착시간']).dt.total_seconds() / 60

# 실제 도착시간이 예상 도착시간보다 늦은 경우를 체크하는 컬럼 생성
df['지연여부'] = df['지연시간'] > 0

# 결제 종류별 지연된 주문의 비율 계산
result = df.groupby('결제종류')['지연여부'].mean()

# 가장 비율이 높은  값
print(round(result.max(), 2))

0.56

### 24.그룹핑 찾기, 값 찾기, 필터링(p176)

In [ ]:
import pandas as pd
# df = pd.read_csv("delivery_time.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/delivery_time.csv")
df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

In [ ]:
# 사용자별로 주문 거리의 합계와 평균 계산
df_distance = df.groupby('user')['거리'].sum()

# 주문 거리의 합계가 50km 이상인 사용자만 필터링
cond1 = df_distance >= 50
df_distance = df_distance[cond1]

# 주문 거리의 합계가 50km 이상인 사용자들의 데이터 필터링
filtered_data = df[df['user'].isin(df_distance.index)]
# print(filtered_data)

# 해당 사용자들의 선호 결제 방식 중 큰 값
payment_method = filtered_data['결제종류'].value_counts()
print(payment_method)
print('*'*50)
print(payment_method[0])

결제종류
카드     48
현금     45
앱결제    36
Name: count, dtype: int64
**************************************************
48

<ipython-input-22-5673b192f7f7>:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(payment_method[0])

### 25.시간 간의 차이 계산(일)(p177)

In [ ]:
import pandas as pd
# df = pd.read_csv("delivery_time.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/delivery_time.csv")
df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

In [ ]:
# 각 사용자별로 첫 주문과 마지막 주문 사이의 시간 간격(일 단위)을 계산
df['주문시간'] = pd.to_datetime(df['주문시간'])
min_order_time = df.groupby('user')['주문시간'].min()
max_order_time = df.groupby('user')['주문시간'].max()
time_interval = (max_order_time - min_order_time).dt.days

# 1회 이하 주문 제외
cond1 = time_interval > 0
m = time_interval[cond1].mean()

# 평균보다 기간이 긴 유저 수
cond2 = time_interval > m
print(len(time_interval[cond2]))

146

### 27.시간 범위, 속도(p179)

In [ ]:
import pandas as pd
# df = pd.read_csv("delivery_time.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part1/ch3/delivery_time.csv")
df.head()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

In [ ]:
# datetime 자료형으로 변경
df['주문시간'] = pd.to_datetime(df['주문시간'])
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'])

# 점심시간 주문 선택
df['시간'] = df['주문시간'].dt.hour
cond1 = df['시간'] >= 10
cond2 = df['시간'] < 13
df = df[cond1 & cond2]

# 속도(km/h) = 거리(km)
df['배달시간'] = df['실제도착시간'] - df['주문시간']
df['배달시간'] = df['배달시간'].dt.total_seconds() / 60 / 60
df['속도'] = df['거리'] / df['배달시간']
# print(df['속도'] >= 50)
print((df['속도'] >= 50).sum())

1

### 28.날짜와 시간, 문자열(p180)

# 제 2유형 연습문제(p205)

## 1.문제정의 -> 각 사람의 소득을 예측하는 문제

## 2.라이브러리 및 데이터 불러오기

In [44]:
# 판다스 라이브러리
import pandas as pd

# 데이터 불러오기
# train = pd.read_csv('train.csv')
# test = pd.read_csv('test.csv')
train = pd.read_csv('https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch2/train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch2/test.csv')

## 3.탐색적 데이터 분석(EDA)

In [45]:
# 데이터 샘플
print(train.shape, test.shape)

(29304, 16) (3257, 15)

In [46]:
train.head()

,id,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,3331,34.0,State-gov,177331,Some-college,10,Married-civ-spouse,Prof-specialty,Husband,Black,Male,4386,0,40.0,United-States,>50K
1,19749,58.0,Private,290661,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40.0,United-States,<=50K
2,1157,48.0,Private,125933,Some-college,10,Widowed,Exec-managerial,Unmarried,Black,Female,0,1669,38.0,United-States,<=50K
3,693,58.0,Private,100313,Some-college,10,Married-civ-spouse,Protective-serv,Husband,White,Male,0,1902,40.0,United-States,>50K
4,12522,41.0,Private,195661,Some-college,10,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,54.0,United-States,<=50K

In [47]:
# 자료형 (타입)
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29304 entries, 0 to 29303
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              29304 non-null  int64
 1   age             29292 non-null  float64
 2   workclass       27642 non-null  object
 3   fnlwgt          29304 non-null  int64
 4   education       29304 non-null  object
 5   education.num   29304 non-null  int64
 6   marital.status  29304 non-null  object
 7   occupation      27636 non-null  object
 8   relationship    29304 non-null  object
 9   race            29304 non-null  object
 10  sex             29304 non-null  object
 11  capital.gain    29304 non-null  int64
 12  capital.loss    29304 non-null  int64
 13  hours.per.week  29291 non-null  float64
 14  native.country  28767 non-null  object
 15  income          29304 non-null  object
dtypes: float64(2), int64(5), object(9)
memory usage: 3.6+ MB

In [48]:
# 수치형 컬럼 통계값 확인(train) -> age에 이상치(마이너스 수치)가 존재
train.describe()

,id,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week
count,29304.000000,29292.000000,2.930400e+04,29304.000000,29304.000000,29304.000000,29291.000000
mean,16264.027880,38.553223,1.897488e+05,10.080842,1093.858722,86.744506,40.434229
std,9384.518323,13.628811,1.055250e+05,2.570824,7477.435640,401.518928,12.324036
min,0.000000,-38.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,8145.750000,28.000000,1.177890e+05,9.000000,0.000000,0.000000,40.000000
50%,16253.500000,37.000000,1.783765e+05,10.000000,0.000000,0.000000,40.000000
75%,24374.250000,48.000000,2.370682e+05,12.000000,0.000000,0.000000,45.000000
max,32560.000000,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [49]:
# 수치형 컬럼 통계값 확인(test)
test.describe()

,id,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week
count,3257.000000,3251.000000,3.257000e+03,3257.000000,3257.000000,3257.000000,3248.000000
mean,16423.704943,38.802830,1.900447e+05,10.079214,931.804728,92.336199,40.468288
std,9535.416746,13.917588,1.057902e+05,2.590118,6496.962999,415.732721,12.598546
min,3.000000,17.000000,1.882700e+04,1.000000,0.000000,0.000000,1.000000
25%,8078.000000,28.000000,1.186520e+05,9.000000,0.000000,0.000000,40.000000
50%,16626.000000,37.000000,1.783190e+05,10.000000,0.000000,0.000000,40.000000
75%,24743.000000,48.000000,2.364360e+05,12.000000,0.000000,0.000000,45.000000
max,32559.000000,90.000000,1.033222e+06,16.000000,99999.000000,3900.000000,99.000000

In [50]:
# 범주형 컬럼 통계값 확인 (train)
train.describe(include='object')

,workclass,education,marital.status,occupation,relationship,race,sex,native.country,income
count,27642,29304,29304,27636,29304,29304,29304,28767,29304
unique,8,16,7,14,6,5,2,41,2
top,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,<=50K
freq,20451,9449,13466,3683,11845,25022,19578,26240,22263

In [51]:
# 범주형 컬럼 통계값 확인 (test)
test.describe(include='object')

,workclass,education,marital.status,occupation,relationship,race,sex,native.country
count,3083,3257,3257,3082,3257,3257,3257,3211
unique,8,16,7,14,6,5,2,37
top,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States
freq,2245,1052,1510,457,1348,2794,2212,2930

In [52]:
# 결측치 (train)
train.isnull().sum()

id                   0
age                 12
workclass         1662
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1668
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week      13
native.country     537
income               0
dtype: int64

In [53]:
# 결측치 (test)
test.isnull().sum()

id                  0
age                 6
workclass         174
fnlwgt              0
education           0
education.num       0
marital.status      0
occupation        175
relationship        0
race                0
sex                 0
capital.gain        0
capital.loss        0
hours.per.week      9
native.country     46
dtype: int64

In [54]:
# label(target)별 개수 확인
train['income'].value_counts()

income
<=50K    22263
>50K      7041
Name: count, dtype: int64

## 4.데이터 전처리

In [55]:
# 1.결측치 처리(결측치가 있다면 필수)
# 2. 이상치 처리(선택)
# 3. 인코딩(범주형 데이터가 있다면 필수)
# 4. 스케일링(선택)

### 1.결측치 처리

#### 결측치 삭제

In [56]:
# 결측치가 있는 데이터(행) 전체 삭제 및 확인 dropna() / 기본값 axis=0
print('처리전 : ', train.shape)
df = train.dropna()
print('처리후 : ', df.shape)

처리전 :  (29304, 16)
처리후 :  (27096, 16)

In [57]:
# 결측치가 있는 특정컬럼 데이터(행)삭제
df = train.dropna(subset=['native.country', 'workclass'])
df.isnull().sum()

id                 0
age               12
workclass          0
fnlwgt             0
education          0
education.num      0
marital.status     0
occupation         6
relationship       0
race               0
sex                0
capital.gain       0
capital.loss       0
hours.per.week    13
native.country     0
income             0
dtype: int64

In [58]:
# 결측치가 있는 컬럼 삭제 dropna(axis=1)
print('처리전: ', train.shape)
df = train.dropna(axis=1)
print('처리후: ', df.shape)

처리전:  (29304, 16)
처리후:  (29304, 11)

In [59]:
# 결측치가 많은 특정 컬럼 삭제 drop
print('처리전: ', train.shape)
df = train.drop(['native.country', 'workclass'], axis=1)
print('처리후: ', df.shape)

처리전:  (29304, 16)
처리후:  (29304, 14)

#### 결측치 채우기(범주형)

In [60]:
# 최빈값
m = train['workclass'].mode()[0]
train['workclass'] = train['workclass'].fillna(m)

m = train['native.country'].mode()[0]
train['native.country'] = train['native.country'].fillna(m)

train.isnull().sum()

id                   0
age                 12
workclass            0
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1668
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week      13
native.country       0
income               0
dtype: int64

In [61]:
# 컬럼을 동시에 사용하기
m = train[['workclass', 'native.country']].mode().iloc[0]
train[['workclass', 'native.country']] = train[['workclass', 'native.country']].fillna(m)

train.isnull().sum()

id                   0
age                 12
workclass            0
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1668
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week      13
native.country       0
income               0
dtype: int64

In [62]:
# 결측값을 새로운 카테고리로 생성 X_train['occupation']
train['occupation'] = train['occupation'].fillna('X')
train.isnull().sum()

id                 0
age               12
workclass          0
fnlwgt             0
education          0
education.num      0
marital.status     0
occupation         0
relationship       0
race               0
sex                0
capital.gain       0
capital.loss       0
hours.per.week    13
native.country     0
income             0
dtype: int64

In [63]:
# test데이터
m = test[['workclass', 'native.country']].mode().iloc[0]
test[['workclass', 'native.country']] = test[['workclass', 'native.country']].fillna(m)
test['occupation'] = test['occupation'].fillna('X')
test.isnull().sum()

id                0
age               6
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    9
native.country    0
dtype: int64

#### 결측치 채우기(수치형)

In [64]:
# age 컬럼 평균값으로 채우기
value = int(train['age'].mean())
print('평균값: ', value)
train['age'] = train['age'].fillna(value)
test['age'] = test['age'].fillna(value)

평균값:  38

In [65]:
# 주당 근무시간 중앙값으로 채우기
val = int(train['hours.per.week'].median())
print('중앙값: ', val)
train['hours.per.week'] = train['hours.per.week'].fillna(val)
test['hours.per.week'] = test['hours.per.week'].fillna(val)

중앙값:  40

In [66]:
train.isnull().sum()

id                0
age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

### 2.이상치 처리

In [67]:
# age 컬럼만을 다루어 본다.
train[train['age'] <= 0]

,id,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
39,29188,-33.0,Private,263561,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,60.0,United-States,>50K
79,14325,-38.0,Private,22245,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60.0,United-States,>50K
26161,4292,-25.0,Private,200681,Some-college,10,Never-married,X,Own-child,White,Male,0,0,40.0,United-States,<=50K

In [68]:
test[test['age'] <= 0]

Empty DataFrame
Columns: [id, age, workclass, fnlwgt, education, education.num, marital.status, occupation, relationship, race, sex, capital.gain, capital.loss, hours.per.week, native.country]
Index: []

In [69]:
# age가 1이상인 데이터만 살림 (참고) test 데이터의 행은 절대로 삭제해서는 안된다.
print(train.shape)
train = train[train['age'] > 0]
print(train.shape)

(29304, 16)
(29301, 16)

### 3.인코딩

#### 원핫(one-hot) 인코딩

In [70]:
y_train = train.pop('income')

In [71]:
train_oh = pd.get_dummies(train)
test_oh = pd.get_dummies(test)
print(train.shape, test.shape, train_oh.shape, test_oh.shape)

(29301, 15) (3257, 15) (29301, 107) (3257, 103)

In [72]:
# train과 test 데이터의 컬럼 수가 일치하여야 한다.
# 인코딩 작업에서 다음의 방법을 사용할 수 있다.
print(train.shape, test.shape)
data = pd.concat([train, test], axis=0)
data_oh = pd.get_dummies(data)
train_oh = data_oh.iloc[:len(train)].copy()
test_oh = data_oh.iloc[len(train):].copy()
print(train_oh.shape, test_oh.shape)   # 행이 같아진다.

(29301, 15) (3257, 15)
(29301, 107) (3257, 107)

#### 레이블(label) 인코딩

In [73]:
# cols = train.select_dtypes(include='object').columns
# cols = train.columns[train.dtypes == object] #방법2
cols = ['workclass', 'education', 'marital.status', 'occupation', 'relationship', 'race', 'sex','native.country']
cols

['workclass',
 'education',
 'marital.status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'native.country']

In [74]:
from sklearn.preprocessing import LabelEncoder

for col in cols:
    le = LabelEncoder()
    train[col] = le.fit_transform(train[col])
    test[col] = le.transform(test[col])

train.head()

,id,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country
0,3331,34.0,6,177331,15,10,2,9,0,2,1,4386,0,40.0,38
1,19749,58.0,3,290661,11,9,2,2,0,4,1,0,0,40.0,38
2,1157,48.0,3,125933,15,10,6,3,4,2,0,0,1669,38.0,38
3,693,58.0,3,100313,15,10,2,10,0,4,1,0,1902,40.0,38
4,12522,41.0,3,195661,15,10,2,13,0,4,1,0,0,54.0,38

### 4.스케일링

In [75]:
# 수치형 컬럼명
cols = ['age', 'fnlwgt', 'education.num', 'capital.gain', 'capital.loss', 'hours.per.week']

In [76]:
# 데이터를 매번 새롭게 불러오기 위해 함수로 제작 함
def get_data():
    train_copy= train.copy()
    test_copy = test.copy()
    return train_copy, test_copy

In [77]:
# 민-맥스 스케일링 MinMaxScaler (모든 값이 0과 1사이)
train_copy, test_copy = get_data()

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
train_copy[cols] = scaler.fit_transform(train_copy[cols])
test_copy[cols] = scaler.transform(test_copy[cols])
print(train_copy[cols].head())

        age    fnlwgt  education.num  capital.gain  capital.loss  \
0  0.232877  0.112092       0.600000       0.04386      0.000000
1  0.561644  0.189060       0.533333       0.00000      0.000000
2  0.424658  0.077184       0.600000       0.00000      0.383150
3  0.561644  0.059785       0.600000       0.00000      0.436639
4  0.328767  0.124541       0.600000       0.00000      0.000000

   hours.per.week
0        0.397959
1        0.397959
2        0.377551
3        0.397959
4        0.540816

In [78]:
# 표준화 StandardScaler (Z-score 정규화, 평균이 0 표준편차가 1인 표준 정규분포로 변경)
train_copy, test_copy = get_data()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_copy[cols] = scaler.fit_transform(train_copy[cols])
test_copy[cols] = scaler.transform(test_copy[cols])
print(train_copy[cols].head())

        age    fnlwgt  education.num  capital.gain  capital.loss  \
0 -0.335121 -0.117705      -0.031462      0.440247     -0.216056
1  1.428590  0.956277      -0.420430     -0.146298     -0.216056
2  0.693710 -0.604783      -0.031462     -0.146298      3.940528
3  1.428590 -0.847573      -0.031462     -0.146298      4.520806
4  0.179295  0.056001      -0.031462     -0.146298     -0.216056

   hours.per.week
0       -0.035121
1       -0.035121
2       -0.197450
3       -0.035121
4        1.101181

In [79]:
# 로버스트 스케일링 : 중앙값과 사분위 값 활용, 이상치 영향 최소화 장점
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
print(train[cols].head(2))
train[cols] = scaler.fit_transform(train[cols])
test[cols] = scaler.transform(test[cols])
print('*'*50)
print(train[cols].head(2))

    age  fnlwgt  education.num  capital.gain  capital.loss  hours.per.week
0  34.0  177331             10          4386             0            40.0
1  58.0  290661              9             0             0            40.0
**************************************************
    age    fnlwgt  education.num  capital.gain  capital.loss  hours.per.week
0 -0.15 -0.008711       0.000000        4386.0           0.0             0.0
1  1.05  0.941438      -0.333333           0.0           0.0             0.0

#### target(label)

In [80]:
y_train.value_counts()

income
<=50K    22262
>50K      7039
Name: count, dtype: int64

In [81]:
target = y_train.map({'<=50K':0, '>50K':1})   # mapping
target.value_counts()

income
0    22262
1     7039
Name: count, dtype: int64

## 5.검증 데이터 분할

In [82]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(train, y_train, test_size=0.2, random_state=123)
print(X_train.shape, X_val.shape, y_train.shape, y_val.shape)  # X_train, X_val의 컬럼 수가 일치해야 한다.

(23440, 15) (5861, 15) (23440,) (5861,)

## 6.머신러닝 학습 및 평가

In [84]:
# 랜덤포레스트
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(random_state=123)
model_rf.fit(X_train, y_train)
pred = model_rf.predict_proba(X_val)  # 각 레이블에 속할 확률 값 반환
print(model_rf.classes_)  # ['<=50K' '>50K']
pred[:10]

['<=50K' '>50K']

array([[1.  , 0.  ],
       [0.93, 0.07],
       [0.  , 1.  ],
       [0.26, 0.74],
       [0.88, 0.12],
       [0.99, 0.01],
       [0.96, 0.04],
       [0.77, 0.23],
       [0.95, 0.05],
       [0.63, 0.37]])

In [85]:
from sklearn.metrics import roc_auc_score
roc_auc = roc_auc_score(y_val, pred[:, 1])
print('roc_auc: ', roc_auc)

roc_auc:  0.9120492993848257

In [86]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
pred = model_rf.predict(X_val)
print('accuracy_score: ', accuracy_score(y_val, pred))
print('f1_score: ', f1_score(y_val, pred, pos_label='>50K'))
print('precision_score: ', precision_score(y_val, pred, pos_label='>50K'))

accuracy_score:  0.8599215150998123
f1_score:  0.6896030245746692
precision_score:  0.7774936061381074

### lightgbm 모델 사용(정형 데이터를 다루는데 많이 사용됨)

In [87]:
# LightGBM
import lightgbm as lgb
from lightgbm import LGBMClassifier

lgbmc = LGBMClassifier(random_state=123, verbose=-1)
lgbmc.fit(X_train, y_train)
pred = lgbmc.predict_proba(X_val)

roc_auc = roc_auc_score(y_val, pred[:,1])
print('roc_auc: ', roc_auc)

roc_auc:  0.9239156748095535

In [89]:
pred = lgbmc.predict(X_val)
accuracy = accuracy_score(y_val, pred)
print('accuracy: ', accuracy)
print('f1_score: ', f1_score(y_val, pred, pos_label='>50K'))
print('precision_score: ', precision_score(y_val, pred, pos_label='>50K'))

accuracy:  0.8662344309844736
f1_score:  0.7091988130563798
precision_score:  0.7810457516339869

## 7.예측 및 결과 파일 생성

In [91]:
pred = lgbmc.predict_proba(test)  # class: 2가지
pred

array([[0.94607618, 0.05392382],
       [0.97535215, 0.02464785],
       [0.98350533, 0.01649467],
       ...,
       [0.94509313, 0.05490687],
       [0.98591759, 0.01408241],
       [0.975617  , 0.024383  ]])

In [92]:
lgbmc.classes_  # pred[:, 1] 사용

array(['<=50K', '>50K'], dtype=object)

In [93]:
submit = pd.DataFrame({'pred': pred[:, 1]})
submit.to_csv('result.csv', index=False)

In [94]:
df = pd.read_csv('result.csv')
df.head()

       pred
0  0.053924
1  0.024648
2  0.016495
3  0.782562
4  0.025132

## chap 03.머신러닝 평가 지표(p235)

### 01.이진 분류 평가지표

In [95]:
# 이진분류 데이터
import pandas as pd
y_true = pd.DataFrame([1, 1, 1, 0, 0, 1, 1, 1, 1, 0]) #실제값
y_pred = pd.DataFrame([1, 0, 1, 1, 0, 0, 0, 1, 1, 0]) #예측값

y_true_str = pd.DataFrame(['A', 'A', 'A', 'B', 'B', 'A', 'A', 'A', 'A', 'B']) #실제값
y_pred_str = pd.DataFrame(['A', 'B', 'A', 'A', 'B', 'B', 'B', 'A', 'A', 'B']) #예측값

In [97]:
# 정확도(Accuracy)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_true, y_pred)
print('accuracy: ', accuracy)

accuracy_str = accuracy_score(y_true_str, y_pred_str)
print('accuracy: ', accuracy_str)

accuracy:  0.6
accuracy:  0.6

In [100]:
# 정밀도(Precision)
from sklearn.metrics import precision_score
precision = precision_score(y_true, y_pred)
print('precision: ', precision)

precision_str = precision_score(y_true_str, y_pred_str, pos_label='A')
print('precision_str: ', precision_str)

precision:  0.8
precision_str:  0.8

In [103]:
# 재현율(Recall)
from sklearn.metrics import recall_score
recall = recall_score(y_true, y_pred)
print('recall: ', recall)

recall_str = recall_score(y_true_str, y_pred_str, pos_label='A')
print('recall_str: ', recall_str)

recall:  0.5714285714285714
recall_str:  0.5714285714285714

In [106]:
# F1 스코어(F1 Score)
from sklearn.metrics import f1_score
f1 = f1_score(y_true, y_pred)
print('f1: ', f1)

f1_str = f1_score(y_true_str, y_pred_str, pos_label='A')
print('f1_str: ', f1_str)

f1:  0.6666666666666666
f1_str:  0.6666666666666666

In [ ]:
# ROC-AUC()