<a href="https://colab.research.google.com/github/va4756/yemoon_bigdata_test/blob/main/bigdata_%EC%98%88%EB%AC%B8_%EC%8B%A4%EC%A0%84%EB%AC%B8%EC%A0%9C_example2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01. 2회 기출문제

## 데이터 동기화

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
!git clone https://github.com/AnalyticsKnight/yemoonsaBigdata/

Cloning into 'yemoonsaBigdata'...
remote: Enumerating objects: 709, done.
remote: Counting objects: 100% (348/348), done.
remote: Compressing objects: 100% (233/233), done.
remote: Total 709 (delta 157), reused 237 (delta 115), pack-reused 361 (from 1)
Receiving objects: 100% (709/709), 11.46 MiB | 11.89 MiB/s, done.
Resolving deltas: 100% (341/341), done.

## 제 1유형 문제

### 문1-1) Boston Housing 데이터셋에서
-  상위 10번째 값으로 상위 10개의 값을 변환하고
- age가 80이상인 데이터를 추출하고
- crim의 평균값 계산

In [4]:
# 데이터 불러오기
import pandas as pd
df = pd.read_csv("/content/yemoonsaBigdata/datasets/Part5/201_boston.csv")
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

In [5]:
# 내림차순으로 정렬(CRIM)
df = df.sort_values(by='CRIM', ascending=False)
df.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
380,88.9762,0.0,18.1,0.0,0.671,6.968,91.9,1.4165,24.0,666.0,20.2,396.90,17.21
418,73.5341,0.0,18.1,0.0,0.679,5.957,100.0,1.8026,24.0,666.0,20.2,16.45,20.62
405,67.9208,0.0,18.1,0.0,0.693,5.683,100.0,1.4254,24.0,666.0,20.2,384.97,22.98
410,51.1358,0.0,18.1,0.0,0.597,5.757,100.0,1.4130,24.0,666.0,20.2,2.60,10.11
414,45.7461,0.0,18.1,0.0,0.693,4.519,100.0,1.6582,24.0,666.0,20.2,88.27,36.98
404,41.5292,0.0,18.1,0.0,0.693,5.531,85.4,1.6074,24.0,666.0,20.2,329.46,27.38
398,38.3518,0.0,18.1,0.0,0.693,5.453,100.0,1.4896,24.0,666.0,20.2,396.90,30.59
427,37.6619,0.0,18.1,0.0,0.679,6.202,78.7,1.8629,24.0,666.0,20.2,18.82,14.52
413,28.6558,0.0,18.1,0.0,0.597,5.155,100.0,1.5894,24.0,666.0,20.2,210.97,20.08
417,25.9406,0.0,18.1,0.0,0.679,5.304,89.1,1.6475,24.0,666.0,20.2,127.36,26.64

In [6]:
# 특정 위치 데이터 찾기(CRIM의 10번째 값)
crim_val = df.iloc[9, 0]  # [10번째 행, 1번째 열] = [9, 0]
crim_val

np.float64(25.9406)

In [7]:
# 특정 위치 데이터 변경하기
df.iloc[:10, 0] = crim_val
df.head(11)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
380,25.9406,0.0,18.1,0.0,0.671,6.968,91.9,1.4165,24.0,666.0,20.2,396.90,17.21
418,25.9406,0.0,18.1,0.0,0.679,5.957,100.0,1.8026,24.0,666.0,20.2,16.45,20.62
405,25.9406,0.0,18.1,0.0,0.693,5.683,100.0,1.4254,24.0,666.0,20.2,384.97,22.98
410,25.9406,0.0,18.1,0.0,0.597,5.757,100.0,1.4130,24.0,666.0,20.2,2.60,10.11
414,25.9406,0.0,18.1,0.0,0.693,4.519,100.0,1.6582,24.0,666.0,20.2,88.27,36.98
404,25.9406,0.0,18.1,0.0,0.693,5.531,85.4,1.6074,24.0,666.0,20.2,329.46,27.38
398,25.9406,0.0,18.1,0.0,0.693,5.453,100.0,1.4896,24.0,666.0,20.2,396.90,30.59
427,25.9406,0.0,18.1,0.0,0.679,6.202,78.7,1.8629,24.0,666.0,20.2,18.82,14.52
413,25.9406,0.0,18.1,0.0,0.597,5.155,100.0,1.5894,24.0,666.0,20.2,210.97,20.08
417,25.9406,0.0,18.1,0.0,0.679,5.304,89.1,1.6475,24.0,666.0,20.2,127.36,26.64
400,25.0461,0.0,18.1,0.0,0.693,5.987,100.0,1.5888,24.0,666.0,20.2,396.90,26.77

In [8]:
# 조건부 평균 계산하기  # 소수 셋째자리까지
cond = df[df['AGE'] >= 80]
result = cond['CRIM'].mean()
print(round(result, 3))

5.759

### 문1-2) Californai Housing 데이터셋에서
- 순서대로 80%의 데이터를 추출하고
- 'total_bedrooms' 변수의 중앙값을 구하고
- 'total_bedrooms'의 결측치에 이 값으로 대체한 후,
- 결측치 대체 전과 후의 표준편차를 구하고
- 이 둘의 차를 절대값으로 구하시오.

In [9]:
import pandas as pd

df = pd.read_csv("/content/yemoonsaBigdata/datasets/Part5/202_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [11]:
# 데이터 추출하기
val_80 = int(len(df) * 0.8)
rst_df = df.iloc[:val_80]['total_bedrooms']
rst_df

0         129.0
1        1106.0
2         190.0
3         235.0
4         280.0
          ...
16507     599.0
16508     331.0
16509     411.0
16510     941.0
16511     417.0
Name: total_bedrooms, Length: 16512, dtype: float64

In [12]:
# 표준편차, 중앙값 계산하기
rst_std = rst_df.std()
rst_med = rst_df.median()
rst_std, rst_med

(435.900577052527, 436.0)

In [13]:
# 결측값 채우기 & 표준편차 계산하기
rst_df_fillna = rst_df.fillna(rst_med)
rst_std_2 = rst_df_fillna.std()
rst_std_2

433.9254297608813

In [14]:
# 결과 출력하기
result = abs(rst_std - rst_std_2)
result

1.975147291645726

### 문1-3) (문1-2)의 Californai Housing 데이터셋에서
- 'population' 컬럼에서 이상치의 갯수를 구하시오
- 이상치를 구하기 위해서는 평균, 1.5X(표준편차) 를 이용한다.

In [15]:
import pandas as pd

df = pd.read_csv("/content/yemoonsaBigdata/datasets/Part5/202_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [17]:
mean = df['population'].mean()
std = df['population'].std()
print(mean, std)

1425.4767441860465 1132.4621217653375

In [23]:
lower_bound = mean - 1.5 * std
upper_bound = mean + 1.5 * std

res_df = df.loc[(df['population'] < lower_bound) | (df['population'] > upper_bound), 'population']
result = res_df.sum()
result

np.float64(5607295.0)

## 제 2유형 문제

### (문제) E-Commerce Shipping 데이터셋이다. 주어진 훈련데이터셋을 이용하여 고객이 주문한 물품의 정시 도착 여부를 예측하고 예측 결과를 CSV 파일로 제출하시오.
- 예측값의 ROC-AUC 점수 결과로 점수를 매김

In [24]:
import pandas as pd
X_test = pd.read_csv("yemoonsaBigdata/datasets/Part5/204_x_test.csv")
X_train = pd.read_csv("yemoonsaBigdata/datasets/Part5/204_x_train.csv")
y_train = pd.read_csv("yemoonsaBigdata/datasets/Part5/204_y_train.csv")

#### 1.데이터 분석 작업

In [25]:
print(X_train.shape, X_test.shape, y_train.shape)

(6599, 11) (4400, 11) (6599, 2)

In [27]:
X_train.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms
0,9902,F,Ship,3,5,214,2,medium,F,6,4578
1,9501,A,Ship,4,2,201,3,medium,F,4,4613
2,6111,A,Ship,4,2,264,3,low,M,10,5137
3,588,F,Ship,3,5,194,2,medium,M,4,3496
4,10806,F,Road,5,5,269,5,medium,F,3,1120

In [26]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6599 entries, 0 to 6598
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   6599 non-null   int64
 1   Warehouse_block      6599 non-null   object
 2   Mode_of_Shipment     6599 non-null   object
 3   Customer_care_calls  6599 non-null   int64
 4   Customer_rating      6599 non-null   int64
 5   Cost_of_the_Product  6599 non-null   int64
 6   Prior_purchases      6599 non-null   int64
 7   Product_importance   6599 non-null   object
 8   Gender               6599 non-null   object
 9   Discount_offered     6599 non-null   int64
 10  Weight_in_gms        6599 non-null   int64
dtypes: int64(7), object(4)
memory usage: 567.2+ KB

In [28]:
y_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6599 entries, 0 to 6598
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   6599 non-null   int64
 1   Reached.on.Time_Y.N  6599 non-null   int64
dtypes: int64(2)
memory usage: 103.2 KB

In [31]:
X_train.isnull().sum()

ID                     0
Warehouse_block        0
Mode_of_Shipment       0
Customer_care_calls    0
Customer_rating        0
Cost_of_the_Product    0
Prior_purchases        0
Product_importance     0
Gender                 0
Discount_offered       0
Weight_in_gms          0
dtype: int64

In [32]:
y_train.isnull().sum()

ID                     0
Reached.on.Time_Y.N    0
dtype: int64

In [33]:
X_train.columns

Index(['ID', 'Warehouse_block', 'Mode_of_Shipment', 'Customer_care_calls',
       'Customer_rating', 'Cost_of_the_Product', 'Prior_purchases',
       'Product_importance', 'Gender', 'Discount_offered', 'Weight_in_gms'],
      dtype='object')

In [34]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6599 entries, 0 to 6598
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   6599 non-null   int64
 1   Warehouse_block      6599 non-null   object
 2   Mode_of_Shipment     6599 non-null   object
 3   Customer_care_calls  6599 non-null   int64
 4   Customer_rating      6599 non-null   int64
 5   Cost_of_the_Product  6599 non-null   int64
 6   Prior_purchases      6599 non-null   int64
 7   Product_importance   6599 non-null   object
 8   Gender               6599 non-null   object
 9   Discount_offered     6599 non-null   int64
 10  Weight_in_gms        6599 non-null   int64
dtypes: int64(7), object(4)
memory usage: 567.2+ KB

#### 2.각각의 열에 대해 분리작업

In [35]:
COL_DEL = ["ID"]
COL_NUM = ['Customer_care_calls', 'Customer_rating', 'Cost_of_the_Product', 'Prior_purchases', 'Discount_offered', 'Weight_in_gms']
COL_CAT = ['Warehouse_block', 'Mode_of_Shipment', 'Product_importance', 'Gender']
COL_Y = ['Reached.on.Time_Y.N']

#### 3.데이터 모형 구축

In [39]:
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(X_train[COL_NUM+COL_CAT],
                                                  y_train[COL_Y],
                                                  test_size=0.3,
                                                  stratify=y_train[COL_Y])
X_tr.shape, X_val.shape, y_tr.shape, y_val.shape

((2263, 10), (970, 10), (2263, 1), (970, 1))

In [40]:
y_train

      Reached.on.Time_Y.N
5327                    1
212                     1
2219                    0
4240                    0
1639                    1
...                   ...
3168                    1
5686                    1
5421                    1
3068                    1
1336                    0

[3233 rows x 1 columns]

#### 4.스케일링 작업 시행

In [41]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_tr[COL_NUM])

X_tr[COL_NUM] = scaler.transform(X_tr[COL_NUM])
X_val[COL_NUM] = scaler.transform(X_val[COL_NUM])
X_test[COL_NUM] = scaler.transform(X_test[COL_NUM])

In [42]:
X_tr[COL_NUM].head()

,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Discount_offered,Weight_in_gms
1129,-0.933083,0.703684,0.707128,-0.386931,-0.701315,1.079176
731,-0.057278,0.703684,-0.529033,-0.386931,-0.192147,1.272893
1288,-0.057278,-0.706176,0.974963,-1.017332,-0.383085,1.039942
4328,-0.057278,-1.411106,1.284004,0.243469,-0.764961,1.206686
896,1.694333,0.703684,1.428223,0.243469,-0.192147,-1.328187

#### 5.인코딩 작업 실시