<a href="https://colab.research.google.com/github/va4756/yemoon_bigdata_test/blob/main/datamanim_%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%A0%84%EC%B2%98%EB%A6%AC_100%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 01.Data Loading

### 01.데이터셋

In [ ]:
# 문제1: 데이터를 로드하라. 데이터는 \t을 기준으로 구분되어있다.
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/lol.csv', sep='\t')
print(df.shape)
df.head()

,gameId,creationTime,gameDuration,seasonId,winner,firstBlood,firstTower,firstInhibitor,firstBaron,firstDragon,...,t2_towerKills,t2_inhibitorKills,t2_baronKills,t2_dragonKills,t2_riftHeraldKills,t2_ban1,t2_ban2,t2_ban3,t2_ban4,t2_ban5
0,3326086514,1504279457970,1949,9,1,2,1,1,1,1,...,5,0,0,1,1,114,67,43,16,51
1,3229566029,1497848803862,1851,9,1,1,1,1,0,1,...,2,0,0,0,0,11,67,238,51,420
2,3327363504,1504360103310,1493,9,1,2,1,1,1,2,...,2,0,0,1,0,157,238,121,57,28
3,3326856598,1504348503996,1758,9,1,1,1,1,1,1,...,0,0,0,0,0,164,18,141,40,51
4,3330080762,1504554410899,2094,9,1,2,1,1,1,1,...,3,0,0,1,0,86,11,201,122,18

In [ ]:
# 문제2: 데이터의 상위 5개 행을 출력하라
df.head(5)

,gameId,creationTime,gameDuration,seasonId,winner,firstBlood,firstTower,firstInhibitor,firstBaron,firstDragon,...,t2_towerKills,t2_inhibitorKills,t2_baronKills,t2_dragonKills,t2_riftHeraldKills,t2_ban1,t2_ban2,t2_ban3,t2_ban4,t2_ban5
0,3326086514,1504279457970,1949,9,1,2,1,1,1,1,...,5,0,0,1,1,114,67,43,16,51
1,3229566029,1497848803862,1851,9,1,1,1,1,0,1,...,2,0,0,0,0,11,67,238,51,420
2,3327363504,1504360103310,1493,9,1,2,1,1,1,2,...,2,0,0,1,0,157,238,121,57,28
3,3326856598,1504348503996,1758,9,1,1,1,1,1,1,...,0,0,0,0,0,164,18,141,40,51
4,3330080762,1504554410899,2094,9,1,2,1,1,1,1,...,3,0,0,1,0,86,11,201,122,18

In [ ]:
# 문제3: 데이터의 행과 열의 갯수를 파악하라
# df.shape
# row, col = df.shape
# row, col
result = df.shape
result

(51490, 61)

In [ ]:
# 문제4: 전체 컬럼을 출력하라
# type(df.columns)
df.columns

Index(['gameId', 'creationTime', 'gameDuration', 'seasonId', 'winner',
       'firstBlood', 'firstTower', 'firstInhibitor', 'firstBaron',
       'firstDragon', 'firstRiftHerald', 't1_champ1id', 't1_champ1_sum1',
       't1_champ1_sum2', 't1_champ2id', 't1_champ2_sum1', 't1_champ2_sum2',
       't1_champ3id', 't1_champ3_sum1', 't1_champ3_sum2', 't1_champ4id',
       't1_champ4_sum1', 't1_champ4_sum2', 't1_champ5id', 't1_champ5_sum1',
       't1_champ5_sum2', 't1_towerKills', 't1_inhibitorKills', 't1_baronKills',
       't1_dragonKills', 't1_riftHeraldKills', 't1_ban1', 't1_ban2', 't1_ban3',
       't1_ban4', 't1_ban5', 't2_champ1id', 't2_champ1_sum1', 't2_champ1_sum2',
       't2_champ2id', 't2_champ2_sum1', 't2_champ2_sum2', 't2_champ3id',
       't2_champ3_sum1', 't2_champ3_sum2', 't2_champ4id', 't2_champ4_sum1',
       't2_champ4_sum2', 't2_champ5id', 't2_champ5_sum1', 't2_champ5_sum2',
       't2_towerKills', 't2_inhibitorKills', 't2_baronKills', 't2_dragonKills',
       't2_riftHeraldKills', 't2_ban1', 't2_ban2', 't2_ban3', 't2_ban4',
       't2_ban5'],
      dtype='object')

In [ ]:
# 문제5: 6번째 컬럼명을 출력하라
result = df.columns[5]
result

'firstBlood'

In [ ]:
# 문제6: 6번째 컬럼의 데이터 타입을 확인하라
# df['firstBlood'].dtype
df[df.columns[5]].dtype

dtype('int64')

In [ ]:
# 문제7: 데이터셋의 인덱스 구성은 어떤가(gameDuration)
df.sort_values('gameDuration', ascending=False).reset_index()

,index,gameId,creationTime,gameDuration,seasonId,winner,firstBlood,firstTower,firstInhibitor,firstBaron,...,t2_towerKills,t2_inhibitorKills,t2_baronKills,t2_dragonKills,t2_riftHeraldKills,t2_ban1,t2_ban2,t2_ban3,t2_ban4,t2_ban5
0,30524,3327791693,1504384857161,4728,9,2,1,1,2,2,...,11,9,2,2,0,134,107,29,53,154
1,50101,3230018445,1497872895195,4562,9,2,2,2,2,1,...,9,4,1,3,0,122,238,117,105,412
2,13583,3329122407,1504466436882,4220,9,2,1,1,1,2,...,11,4,2,2,0,29,11,67,53,238
3,25416,3329569062,1504529046227,4210,9,2,2,1,2,1,...,11,6,2,3,0,64,119,23,157,11
4,7989,3316170772,1503566185019,4132,9,2,2,1,1,2,...,8,3,1,2,0,157,51,45,497,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51485,45845,3308449378,1503054002498,191,9,2,0,0,0,0,...,0,0,0,0,0,122,74,8,53,157
51486,47087,3329980283,1504551645575,191,9,1,0,0,0,0,...,0,0,0,0,0,114,-1,38,117,40
51487,34226,3296144417,1502284120915,191,9,2,0,0,0,0,...,0,0,0,0,0,51,31,9,157,75
51488,46157,3331593233,1504682337714,190,9,2,2,0,0,0,...,0,0,0,0,0,18,157,40,57,55
51489,5405,3326389082,1504297218541,190,9,1,2,0,0,0,...,0,0,0,0,0,16,35,18,29,40

In [ ]:
# 문제8: 6번째 컬럼의 3번째 값은 무엇인가?
df[df.columns[5]][2]

np.int64(2)

In [ ]:
df.iloc[5, 2] # df.iloc[행, 열]

np.int64(2)

### 02.데이터셋

In [ ]:
# 문제9: 데이터를 로드하라. 컬럼이 한글이기에 적절한 처리해줘야함
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/Jeju.csv', encoding='cp949')
print(df.shape)
df.head()

(9621, 13)

,id,일자,시도명,읍면동명,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
0,22448,2018-01-01,제주시,도두동,32249.987,3418.266,102709.092,138377.345,39.556,29.167,5.0,0.0,2.5
1,22449,2018-01-01,제주시,외도동,213500.997,10341.172,112692.789,336534.958,32.900,30.900,5.0,0.0,2.5
2,22450,2018-01-01,제주시,이도2동,1212382.218,96920.834,541194.481,1850497.533,29.538,35.692,2.9,0.0,2.4
3,22451,2018-01-01,제주시,일도1동,33991.653,6034.253,72155.919,112181.825,30.000,23.500,2.9,0.0,2.4
4,22452,2018-01-01,서귀포시,대천동,155036.925,9403.969,150882.409,315323.303,41.583,14.375,5.1,0.0,2.3

In [ ]:
# 문제 10: 데이터 마지막 3개행을 출력하라
df.tail(3)

,id,일자,시도명,읍면동명,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
9618,32066,2020-04-30,제주시,도두동,28397.481,3144.895,84052.697,115595.073,41.053,29.421,20.3,0.0,3.0
9619,32067,2020-04-30,서귀포시,안덕면,348037.846,29106.286,251129.660,628273.792,46.595,49.189,17.6,0.0,3.5
9620,32068,2020-04-30,제주시,연동,1010643.372,65673.477,447622.068,1523938.917,40.863,27.765,14.1,0.0,4.8

In [ ]:
# 문제 11: 수치형 변수를 가진 컬럼을 출력하라
# df.info()
df_num = df.select_dtypes(exclude='object')
result = df_num.columns
result

Index(['id', '거주인구', '근무인구', '방문인구', '총 유동인구', '평균 속도', '평균 소요 시간', '평균 기온',
       '일강수량', '평균 풍속'],
      dtype='object')

In [ ]:
# 문제 12: 범주형 변수를 가진 컬럼을 출력하라
df_obj = df.select_dtypes(include='object').columns
df_obj

Index(['일자', '시도명', '읍면동명'], dtype='object')

In [ ]:
# 문제 12: 범주형 변수를 가진 컬럼을 출력하라
df.select_dtypes(include='object').columns

Index(['일자', '시도명', '읍면동명'], dtype='object')

In [ ]:
# 문제 13:각 컬럼의 결측치 숫자를 파악하라
df.isnull().sum()

id          0
일자          0
시도명         0
읍면동명        0
거주인구        0
근무인구        0
방문인구        0
총 유동인구      0
평균 속도       0
평균 소요 시간    0
평균 기온       0
일강수량        0
평균 풍속       0
dtype: int64

In [ ]:
# 문제14: 각 컬럼의 데이터수, 데이터타입을 한번에 확인하라
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9621 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        9621 non-null   int64
 1   일자        9621 non-null   object
 2   시도명       9621 non-null   object
 3   읍면동명      9621 non-null   object
 4   거주인구      9621 non-null   float64
 5   근무인구      9621 non-null   float64
 6   방문인구      9621 non-null   float64
 7   총 유동인구    9621 non-null   float64
 8   평균 속도     9621 non-null   float64
 9   평균 소요 시간  9621 non-null   float64
 10  평균 기온     9621 non-null   float64
 11  일강수량      9621 non-null   float64
 12  평균 풍속     9621 non-null   float64
dtypes: float64(9), int64(1), object(3)
memory usage: 977.3+ KB

In [ ]:
#문제15: 각 수치형 변수의 분포(사분위, 평균, 표준편차, 최대 , 최소)를 확인하라
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,9621.0,27258.000000,2777.487804,22448.000,24853.000,27258.000,29663.000,32068.000
거주인구,9621.0,317431.480541,298207.949076,9305.552,95399.394,222110.460,410667.056,1364503.913
근무인구,9621.0,35471.201510,40381.214775,1407.936,12074.498,21960.928,40192.032,263476.965
방문인구,9621.0,195889.561802,140706.090325,11538.322,99632.153,152805.335,236325.109,723459.209
총 유동인구,9621.0,548792.243858,460880.237722,22251.810,221690.987,386693.468,640691.811,2066483.867
평균 속도,9621.0,41.109084,8.758631,24.333,34.250,39.640,49.105,103.000
평균 소요 시간,9621.0,37.215873,12.993786,12.667,27.889,34.500,46.176,172.200
평균 기온,9621.0,13.550828,7.745515,-9.600,7.600,13.400,19.700,30.400
일강수량,9621.0,6.972426,27.617260,0.000,0.000,0.000,1.500,587.500
평균 풍속,9621.0,2.753171,1.498538,0.000,1.700,2.400,3.400,13.333

In [ ]:
#문제16: 거주인구 컬럼의 값들을 출력하라
print(type(df['거주인구']))
print(type(df[['거주인구']]))
df[['거주인구']]

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

             거주인구
0       32249.987
1      213500.997
2     1212382.218
3       33991.653
4      155036.925
...           ...
9616   228260.005
9617   459959.064
9618    28397.481
9619   348037.846
9620  1010643.372

[9621 rows x 1 columns]

In [ ]:
# 또는
df.iloc[:, 4]   # df.iloc['행', '열']

0         32249.987
1        213500.997
2       1212382.218
3         33991.653
4        155036.925
           ...
9616     228260.005
9617     459959.064
9618      28397.481
9619     348037.846
9620    1010643.372
Name: 거주인구, Length: 9621, dtype: float64

In [ ]:
#문제17: 평균 속도 컬럼의 4분위 범위(IQR) 값을 구하여라
df[['평균 속도']]
iqr = df['평균 속도'].quantile(0.75) - df['평균 속도'].quantile(0.25)
round(iqr, 2)

np.float64(14.85)

In [ ]:
#문제18: 읍면동명 컬럼의 유일값 갯수를 출력하라
len(df['읍면동명'].unique())

41

In [ ]:
lst = []
for v in df['읍면동명'].values:
    if v not in lst:
        lst.append(v)
lst

['도두동',
 '외도동',
 '이도2동',
 '일도1동',
 '대천동',
 '서홍동',
 '한경면',
 '송산동',
 '조천읍',
 '일도2동',
 '영천동',
 '예래동',
 '대륜동',
 '삼도1동',
 '이호동',
 '건입동',
 '중앙동',
 '삼양동',
 '삼도2동',
 '이도1동',
 '남원읍',
 '대정읍',
 '정방동',
 '효돈동',
 '아라동',
 '한림읍',
 '구좌읍',
 '용담1동',
 '오라동',
 '화북동',
 '연동',
 '표선면',
 '중문동',
 '성산읍',
 '안덕면',
 '천지동',
 '노형동',
 '동홍동',
 '용담2동',
 '봉개동',
 '애월읍']

In [ ]:
#문제19: 읍면동명 컬럼의 유일값을 모두 출력하라
df['읍면동명'].unique()

array(['도두동', '외도동', '이도2동', '일도1동', '대천동', '서홍동', '한경면', '송산동', '조천읍',
       '일도2동', '영천동', '예래동', '대륜동', '삼도1동', '이호동', '건입동', '중앙동', '삼양동',
       '삼도2동', '이도1동', '남원읍', '대정읍', '정방동', '효돈동', '아라동', '한림읍', '구좌읍',
       '용담1동', '오라동', '화북동', '연동', '표선면', '중문동', '성산읍', '안덕면', '천지동',
       '노형동', '동홍동', '용담2동', '봉개동', '애월읍'], dtype=object)

## 02.Fitering and Sorting

In [ ]:
#문제20: 데이터를 로드하라.
import pandas as pd   # 식당데이터
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/chipo.csv', encoding='cp949')
print(df.shape)
df.head()

(4622, 5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [ ]:
#문제21: quantity컬럼 값이 3인 데이터를 추출하여 첫 5행을 출력하라
cond = (df['quantity'] == 3)
print(type(cond))
df[cond].head()

<class 'pandas.core.series.Series'>

,order_id,quantity,item_name,choice_description,item_price
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20
689,284,3,Canned Soft Drink,[Diet Coke],$3.75
818,338,3,Bottled Water,NaN,$3.27
850,350,3,Canned Soft Drink,[Sprite],$3.75

In [ ]:
cond = df.loc[df['quantity'] == 3]
cond.head()

,order_id,quantity,item_name,choice_description,item_price
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20
689,284,3,Canned Soft Drink,[Diet Coke],$3.75
818,338,3,Bottled Water,NaN,$3.27
850,350,3,Canned Soft Drink,[Sprite],$3.75

In [ ]:
#문제22: quantity컬럼 값이 3인 데이터를 추출하여 index를 0부터 정렬하고 첫 5행을 출력하라
result = df.loc[df['quantity'] == 3].reset_index(drop=True)
result.head()

,order_id,quantity,item_name,choice_description,item_price
0,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
1,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20
2,284,3,Canned Soft Drink,[Diet Coke],$3.75
3,338,3,Bottled Water,NaN,$3.27
4,350,3,Canned Soft Drink,[Sprite],$3.75

In [ ]:
#문제23: quantity , item_price 두개의 컬럼으로 구성된 새로운 데이터 프레임을 정의하라
df_new = df[['quantity', 'item_price']].copy()
df_new

      quantity item_price
0            1     $2.39
1            1     $3.39
2            1     $3.39
3            1     $2.39
4            2    $16.98
...        ...        ...
4617         1    $11.75
4618         1    $11.75
4619         1    $11.25
4620         1     $8.75
4621         1     $8.75

[4622 rows x 2 columns]

In [ ]:
a = '$11.75'
a.replace('$', '')

'11.75'

In [ ]:
#문제24: item_price 컬럼의 달러표시 문자를 제거하고 float 타입으로 저장하여 new_price 컬럼에 저장하라
df['new_price'] = df['item_price'].str.replace('$', '', regex=False).astype(float)
df['new_price']

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: new_price, Length: 4622, dtype: float64

In [ ]:
df.head()

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
1,1,1,Izze,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98

In [ ]:
#문제25: new_price 컬럼이 5이하의 값을 가지는 데이터프레임을 추출하고, 전체 갯수를 구하여라
result = df.loc[df['new_price'] <= 5].value_counts()
result

order_id  quantity  item_name          choice_description  item_price  new_price
1011      1         Canned Soft Drink  [Coke]              $1.25       1.25         3
724       1         Canned Soft Drink  [Coke]              $1.25       1.25         3
233       1         Canned Soft Drink  [Diet Coke]         $1.25       1.25         2
940       1         Canned Soft Drink  [Coke]              $1.25       1.25         2
507       1         Canned Soft Drink  [Lemonade]          $1.25       1.25         2
                                                                                   ..
569       1         Canned Soft Drink  [Diet Coke]         $1.25       1.25         1
567       1         Canned Soda        [Coca Cola]         $1.09       1.09         1
564       1         Canned Soft Drink  [Diet Coke]         $1.25       1.25         1
561       2         Canned Soft Drink  [Lemonade]          $2.50       2.50         1
609       1         Canned Soft Drink  [Diet Coke]         $1.25       1.25         1
Name: count, Length: 436, dtype: int64

In [ ]:
df['item_name'].unique()

array(['Chips and Fresh Tomato Salsa', 'Izze', 'Nantucket Nectar',
       'Chips and Tomatillo-Green Chili Salsa', 'Chicken Bowl',
       'Side of Chips', 'Steak Burrito', 'Steak Soft Tacos',
       'Chips and Guacamole', 'Chicken Crispy Tacos',
       'Chicken Soft Tacos', 'Chicken Burrito', 'Canned Soda',
       'Barbacoa Burrito', 'Carnitas Burrito', 'Carnitas Bowl',
       'Bottled Water', 'Chips and Tomatillo Green Chili Salsa',
       'Barbacoa Bowl', 'Chips', 'Chicken Salad Bowl', 'Steak Bowl',
       'Barbacoa Soft Tacos', 'Veggie Burrito', 'Veggie Bowl',
       'Steak Crispy Tacos', 'Chips and Tomatillo Red Chili Salsa',
       'Barbacoa Crispy Tacos', 'Veggie Salad Bowl',
       'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa', 'Carnitas Soft Tacos',
       'Chicken Salad', 'Canned Soft Drink', 'Steak Salad Bowl',
       '6 Pack Soft Drink', 'Chips and Tomatillo-Red Chili Salsa', 'Bowl',
       'Burrito', 'Crispy Tacos', 'Carnitas Crispy Tacos', 'Steak Salad',
       'Chips and Mild Fresh Tomato Salsa', 'Veggie Soft Tacos',
       'Carnitas Salad Bowl', 'Barbacoa Salad Bowl', 'Salad',
       'Veggie Crispy Tacos', 'Veggie Salad', 'Carnitas Salad'],
      dtype=object)

In [ ]:
#문제26: item_name명이 Chicken Salad Bowl 인 데이터 프레임을 추출하라고 index 값을 초기화 하여라
df.loc[df['item_name'] == 'Chicken Salad Bowl'].reset_index(drop=True)

,order_id,quantity,item_name,choice_description,item_price,new_price
0,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75
1,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",$22.50,22.50
2,94,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$22.50,22.50
3,111,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
4,137,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, Fajita Vegetables]",$17.50,17.50
...,...,...,...,...,...,...
105,1813,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$17.50,17.50
106,1822,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Gua...",$11.25,11.25
107,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
108,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
109,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

In [ ]:
#문제27: new_price값이 9 이하이고 item_name 값이 Chicken Salad Bowl 인 데이터 프레임을 추출하라
df.loc[(df['new_price'] <= 9) & (df['item_name'] == 'Chicken Salad Bowl')].shape

(56, 6)

In [ ]:
#문제28: df의 new_price 컬럼 값에 따라 오름차순으로 정리하고 index를 초기화 하여라
df.sort_values(by='new_price', ascending=True).reset_index(drop=True)

,order_id,quantity,item_name,choice_description,item_price,new_price
0,17,1,Bottled Water,NaN,$1.09,1.09
1,24,1,Canned Soda,[Sprite],$1.09,1.09
2,388,1,Bottled Water,NaN,$1.09,1.09
3,496,1,Canned Soda,[Diet Coke],$1.09,1.09
4,496,1,Canned Soda,[Diet Dr. Pepper],$1.09,1.09
...,...,...,...,...,...,...
4617,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$33.75,33.75
4618,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$35.00,35.00
4619,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$35.00,35.00
4620,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$35.25,35.25
4621,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25,44.25

In [ ]:
#문제29: df의 item_name 컬럼 값중 Chips 포함하는 경우의 데이터를 출력하라
df.loc[df['item_name'].str.contains('Chips')]

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
6,3,1,Side of Chips,NaN,$1.69,1.69
10,5,1,Chips and Guacamole,NaN,$4.45,4.45
14,7,1,Chips and Guacamole,NaN,$4.45,4.45
...,...,...,...,...,...,...
4596,1826,1,Chips and Guacamole,NaN,$4.45,4.45
4600,1827,1,Chips and Guacamole,NaN,$4.45,4.45
4605,1828,1,Chips and Guacamole,NaN,$4.45,4.45
4613,1831,1,Chips,NaN,$2.15,2.15
4616,1832,1,Chips and Guacamole,NaN,$4.45,4.45

In [ ]:
df.loc[df['item_name'].str.contains('Chips')]['item_name'].unique()

array(['Chips and Fresh Tomato Salsa',
       'Chips and Tomatillo-Green Chili Salsa', 'Side of Chips',
       'Chips and Guacamole', 'Chips and Tomatillo Green Chili Salsa',
       'Chips', 'Chips and Tomatillo Red Chili Salsa',
       'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa',
       'Chips and Tomatillo-Red Chili Salsa',
       'Chips and Mild Fresh Tomato Salsa'], dtype=object)

In [ ]:
#문제30: df의 짝수번째 컬럼만을 포함하는 데이터프레임을 출력하라
df.iloc[:, ::2]

      order_id                              item_name item_price
0            1           Chips and Fresh Tomato Salsa     $2.39
1            1                                   Izze     $3.39
2            1                       Nantucket Nectar     $3.39
3            1  Chips and Tomatillo-Green Chili Salsa     $2.39
4            2                           Chicken Bowl    $16.98
...        ...                                    ...        ...
4617      1833                          Steak Burrito    $11.75
4618      1833                          Steak Burrito    $11.75
4619      1834                     Chicken Salad Bowl    $11.25
4620      1834                     Chicken Salad Bowl     $8.75
4621      1834                     Chicken Salad Bowl     $8.75

[4622 rows x 3 columns]

In [ ]:
#문제31: df의 new_price 컬럼 값에 따라 내림차순으로 정리하고 index를 초기화 하여라
df.sort_values(by='new_price', ascending=False).reset_index(drop=True)

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25,44.25
1,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$35.25,35.25
2,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$35.00,35.00
3,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$35.00,35.00
4,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$33.75,33.75
...,...,...,...,...,...,...
4617,435,1,Canned Soda,[Mountain Dew],$1.09,1.09
4618,51,1,Canned Soda,[Diet Dr. Pepper],$1.09,1.09
4619,1014,1,Canned Soda,[Coca Cola],$1.09,1.09
4620,1009,1,Canned Soda,[Diet Coke],$1.09,1.09
4621,1009,1,Bottled Water,NaN,$1.09,1.09

In [ ]:
#문제32: df의 item_name 컬럼 값이 Steak Salad 또는 Bowl 인 데이터를 인덱싱하라
df.loc[(df['item_name'] == 'Steak Salad') | (df['item_name'] == 'Bowl')]

,order_id,quantity,item_name,choice_description,item_price,new_price
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20,22.20
664,276,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99
673,279,1,Bowl,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",$7.40,7.40
752,311,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99
893,369,1,Steak Salad,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$8.99,8.99
3502,1406,1,Steak Salad,"[[Lettuce, Fajita Veggies]]",$8.69,8.69

In [ ]:
#문제33: df의 item_name 컬럼 값이 Steak Salad 또는 Bowl 인 데이터를 데이터 프레임화 한 후,
# item_name를 기준으로 중복행이 있으면 제거하되 첫번째 케이스만 남겨라
res_df = df.loc[(df['item_name'] == 'Steak Salad') | (df['item_name'] == 'Bowl')]
res_df.drop_duplicates(subset='item_name', keep='first')

,order_id,quantity,item_name,choice_description,item_price,new_price
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20,22.20
664,276,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99

In [ ]:
#문제34: df의 item_name 컬럼 값이 Steak Salad 또는 Bowl 인 데이터를 데이터 프레임화 한 후,
# item_name를 기준으로 중복행이 있으면 제거하되 마지막 케이스만 남겨라
rst_df = df.loc[(df['item_name'] == 'Steak Salad') | (df['item_name'] == 'Bowl')]
rst_df.drop_duplicates('item_name', keep='last')

,order_id,quantity,item_name,choice_description,item_price,new_price
673,279,1,Bowl,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",$7.40,7.40
3502,1406,1,Steak Salad,"[[Lettuce, Fajita Veggies]]",$8.69,8.69

In [ ]:
#문제35: df의 데이터 중 new_price값이 new_price값의 평균값 이상을 가지는 데이터들을 인덱싱하라
df.loc[(df['new_price']) >= (df['new_price'].mean())]

,order_id,quantity,item_name,choice_description,item_price,new_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98,10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25,9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25,9.25
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

In [ ]:
#문제36: df의 데이터 중 item_name의 값이 Izze 데이터를 Fizzy Lizzy로 수정하라
df.loc[df['item_name'] == 'Izze', 'item_name'] = 'Fizzy Lizzy'
result = df
result.head()

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
1,1,1,Fizzy Lizzy,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98

In [ ]:
#문제37: df의 데이터 중 choice_description 값이 NaN 인 데이터의 갯수
df.loc[df['choice_description'].isnull().sum()]

order_id                                                      508
quantity                                                        1
item_name                                              Steak Bowl
choice_description    [Fresh Tomato Salsa (Mild), [Rice, Cheese]]
item_price                                                 $8.99
new_price                                                    8.99
Name: 1246, dtype: object

In [ ]:
#문제38: df의 데이터 중 choice_description 값이 NaN 인 데이터를 NoData 값으로 대체하라(loc 이용)
df.loc[df['choice_description'].isnull(), 'choice_description'] = 'NoData'
df

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NoData,$2.39,2.39
1,1,1,Fizzy Lizzy,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NoData,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

In [ ]:
#문제39: df의 데이터 중 choice_description 값에 Black이 들어가는 경우를 인덱싱하라
df1 = df.copy()
result = df1.loc[df1['choice_description'].str.contains('Black')]
result

,order_id,quantity,item_name,choice_description,item_price,new_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75,11.75
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25,9.25
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75,8.75
...,...,...,...,...,...,...
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75,8.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25,11.25
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$11.25,11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25,9.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75

In [ ]:
#문제40: df의 데이터 중 choice_description 값에 Vegetables 들어가지 않는 경우의 갯수를 출력하라
df1.loc[~df1['choice_description'].str.contains('Vegetables')].shape[0]   # 이 중에서 row 의 갯수만 구한다.

3900

In [ ]:
#문제41: df의 데이터 중 item_name 값이 N으로 시작하는 데이터를 모두 추출하라
df1.loc[df1['item_name'].str[0] == 'N']

,order_id,quantity,item_name,choice_description,item_price,new_price
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
105,46,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
173,77,1,Nantucket Nectar,[Apple],$3.39,3.39
205,91,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
436,189,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
601,247,2,Nantucket Nectar,[Pineapple Orange Banana],$6.78,6.78
925,381,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
1356,553,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
1585,641,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
1626,656,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
1706,690,1,Nantucket Nectar,[Apple],$3.39,3.39
2162,872,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
2379,947,2,Nantucket Nectar,[Peach Orange],$6.78,6.78
2381,947,1,Nantucket Nectar,[Apple],$3.39,3.39
2430,965,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
2653,1053,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
2818,1118,1,Nantucket Nectar,[Apple],$3.39,3.39
2838,1128,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
2853,1133,1,Nantucket Nectar,[Apple],$3.39,3.39
2949,1172,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
3318,1330,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
3368,1351,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
3570,1433,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
3845,1541,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
4019,1609,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
4078,1632,1,Nantucket Nectar,[Peach Orange],$3.39,3.39

### using sorting data 2

In [ ]:
import pandas as pd   # 식당데이터
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/chipo.csv', encoding='cp949')
print(df.shape)
df.head()

(4622, 5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [ ]:
#문제42: df의 데이터 중 item_name 값의 단어갯수가 15개 이상인 데이터를 인덱싱하라
df.loc[df['item_name'].str.len() >= 15]

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45
...,...,...,...,...,...
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,NaN,$4.45
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
#문제43: df의 데이터 중 new_price값이 lst에 해당하는 경우의 데이터 프레임을 구하고 그 갯수를 출력하라
# lst =[1.69, 2.39, 3.39, 4.45, 9.25, 10.98, 11.75, 16.98]
df['new_price'] = df['item_price'].str.replace('$', '', regex=False).astype(float)
df['new_price']

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: new_price, Length: 4622, dtype: float64

In [ ]:
lst =[1.69, 2.39, 3.39, 4.45, 9.25, 10.98, 11.75, 16.98]

In [ ]:
res_df = df.loc[df['new_price'].isin(lst)]
res_df

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
1,1,1,Izze,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
...,...,...,...,...,...,...
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25,9.25
4616,1832,1,Chips and Guacamole,NaN,$4.45,4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75

In [ ]:
res_df.shape[0]

1393

## 03.Grouping

In [ ]:
import pandas as pd   # 뉴욕 airBnB dataset
#문제44: 데이터를 로드하고 상위 5개 컬럼을 출력하라
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/AB_NYC_2019.csv')
print(df.shape)
df.head()

(48895, 16)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [ ]:
#문제45: 데이터의 각 host_name의 빈도수를 구하고 host_name으로 정렬하여 상위 5개를 출력하라
df['host_name'].value_counts().sort_values(ascending=False).head()

host_name
Michael         417
David           403
Sonder (NYC)    327
John            294
Alex            279
Name: count, dtype: int64

In [ ]:
#문제46: 데이터의 각 host_name의 빈도수를 구하고 빈도수 기준 내림차순 정렬한 데이터 프레임을 만들어라.
# 빈도수 컬럼은 counts로 명명하라
res_df= df['host_name'].value_counts().to_frame()
res_df

               count
host_name
Michael          417
David            403
Sonder (NYC)     327
John             294
Alex             279
...              ...
Pujan              1
Raheem             1
Rusaa              1
Erin At Bedly      1
Brad & Rachel      1

[11452 rows x 1 columns]

In [ ]:
res_df.columns = ['counts']
res_df

               counts
host_name
Michael           417
David             403
Sonder (NYC)      327
John              294
Alex              279
...               ...
Pujan               1
Raheem              1
Rusaa               1
Erin At Bedly       1
Brad & Rachel       1

[11452 rows x 1 columns]

In [ ]:
#문제47: neighbourhood_group의 값에 따른 neighbourhood컬럼 값의 갯수를 구하여라
df[['neighbourhood_group', 'neighbourhood']].groupby(['neighbourhood_group', 'neighbourhood'], as_index=False).size()

    neighbourhood_group  neighbourhood  size
0                 Bronx       Allerton    42
1                 Bronx     Baychester     7
2                 Bronx        Belmont    24
3                 Bronx      Bronxdale    19
4                 Bronx    Castle Hill     9
..                  ...            ...   ...
216       Staten Island    Tottenville     7
217       Staten Island  West Brighton    18
218       Staten Island    Westerleigh     2
219       Staten Island    Willowbrook     1
220       Staten Island        Woodrow     1

[221 rows x 3 columns]

In [ ]:
#문제48: neighbourhood_group의 값에 따른 neighbourhood컬럼 값 중
# neighbourhood_group그룹의 최댓값들을 출력하라
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [ ]:
df_new = df[['neighbourhood_group', 'neighbourhood']].groupby(['neighbourhood_group', 'neighbourhood'], as_index=False).size()
df_new

    neighbourhood_group  neighbourhood  size
0                 Bronx       Allerton    42
1                 Bronx     Baychester     7
2                 Bronx        Belmont    24
3                 Bronx      Bronxdale    19
4                 Bronx    Castle Hill     9
..                  ...            ...   ...
216       Staten Island    Tottenville     7
217       Staten Island  West Brighton    18
218       Staten Island    Westerleigh     2
219       Staten Island    Willowbrook     1
220       Staten Island        Woodrow     1

[221 rows x 3 columns]

In [ ]:
res_df = df_new.sort_values(['neighbourhood_group', 'size'], ascending=[True, False])
res_df

    neighbourhood_group neighbourhood  size
18                Bronx   Kingsbridge    70
15                Bronx       Fordham    63
19                Bronx      Longwood    62
24                Bronx    Mott Haven    60
9                 Bronx     Concourse    50
..                  ...           ...   ...
199       Staten Island      New Dorp     1
206       Staten Island  Richmondtown     1
208       Staten Island     Rossville     1
219       Staten Island   Willowbrook     1
220       Staten Island       Woodrow     1

[221 rows x 3 columns]

In [ ]:
res_df.drop_duplicates('neighbourhood_group', keep='first')

    neighbourhood_group neighbourhood  size
18                Bronx   Kingsbridge    70
93             Brooklyn  Williamsburg  3920
105           Manhattan        Harlem  2658
128              Queens       Astoria   900
212       Staten Island    St. George    48

In [ ]:
#문제49: neighbourhood_group 값에 따른 price값의 평균, 분산, 최대, 최소 값을 구하여라
df[['neighbourhood_group', 'price']].groupby('neighbourhood_group').agg(['mean', 'var', 'max', 'min'])

                          price
                           mean           var    max min
neighbourhood_group
Bronx                 87.496792  11386.885081   2500   0
Brooklyn             124.383207  34921.719135  10000   0
Manhattan            196.875814  84904.159185  10000   0
Queens                99.517649  27923.130227  10000  10
Staten Island        114.812332  77073.088342   5000  13

In [ ]:
#문제50: neighbourhood_group 값에 따른 reviews_per_month 평균, 분산, 최대, 최소 값을 구하여라
df[['neighbourhood_group', 'reviews_per_month']].groupby('neighbourhood_group').agg(['mean', 'var', 'max', 'min'])

                    reviews_per_month
                                 mean       var    max   min
neighbourhood_group
Bronx                        1.837831  2.799878  10.34  0.02
Brooklyn                     1.283212  2.299040  14.00  0.01
Manhattan                    1.272131  2.651206  58.50  0.01
Queens                       1.941200  4.897848  20.94  0.01
Staten Island                1.872580  2.840895  10.12  0.02

In [ ]:
#문제51: neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 구하라
df.groupby(['neighbourhood', 'neighbourhood_group'])['price'].mean()

neighbourhood    neighbourhood_group
Allerton         Bronx                   87.595238
Arden Heights    Staten Island           67.250000
Arrochar         Staten Island          115.000000
Arverne          Queens                 171.779221
Astoria          Queens                 117.187778
                                           ...
Windsor Terrace  Brooklyn               138.993631
Woodhaven        Queens                  67.170455
Woodlawn         Bronx                   60.090909
Woodrow          Staten Island          700.000000
Woodside         Queens                  85.097872
Name: price, Length: 221, dtype: float64

In [ ]:
#문제52: neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 계층적 indexing 없이 구하라
df.groupby(['neighbourhood', 'neighbourhood_group'], as_index=False)['price'].mean()

       neighbourhood neighbourhood_group       price
0           Allerton               Bronx   87.595238
1      Arden Heights       Staten Island   67.250000
2           Arrochar       Staten Island  115.000000
3            Arverne              Queens  171.779221
4            Astoria              Queens  117.187778
..               ...                 ...         ...
216  Windsor Terrace            Brooklyn  138.993631
217        Woodhaven              Queens   67.170455
218         Woodlawn               Bronx   60.090909
219          Woodrow       Staten Island  700.000000
220         Woodside              Queens   85.097872

[221 rows x 3 columns]

In [ ]:
#문제53: neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 계층적 indexing 없이 구하고
# nan 값은 -999값으로 채워라
df_1= df.groupby(['neighbourhood', 'neighbourhood_group'])['price'].mean()
df_1

neighbourhood    neighbourhood_group
Allerton         Bronx                   87.595238
Arden Heights    Staten Island           67.250000
Arrochar         Staten Island          115.000000
Arverne          Queens                 171.779221
Astoria          Queens                 117.187778
                                           ...
Windsor Terrace  Brooklyn               138.993631
Woodhaven        Queens                  67.170455
Woodlawn         Bronx                   60.090909
Woodrow          Staten Island          700.000000
Woodside         Queens                  85.097872
Name: price, Length: 221, dtype: float64

In [ ]:
df_1.isnull().sum()

np.int64(0)

In [ ]:
df['neighbourhood_group'].unique()

array(['Brooklyn', 'Manhattan', 'Queens', 'Staten Island', 'Bronx'],
      dtype=object)

In [ ]:
#문제54: 데이터중 neighbourhood_group 값이 Queens값을 가지는 데이터들 중
# neighbourhood 그룹별로 price값의 평균, 분산, 최대, 최소값을 구하라
df_1 = df.loc[df['neighbourhood_group'] == 'Queens']
df_1

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
46,12937,"1 Stop fr. Manhattan! Private Suite,Landmark B...",50124,Orestes,Queens,Long Island City,40.74771,-73.94740,Private room,130,3,248,2019-07-01,2.25,1,215
77,18198,Little King of Queens,70091,Justin,Queens,Woodside,40.75038,-73.90334,Private room,70,30,25,2019-05-31,0.22,1,324
143,32363,Fully Furnished Basement Apartment,140025,Fredah,Queens,Flushing,40.74028,-73.83168,Private room,140,2,1,2011-09-19,0.01,1,1
161,39593,"A room w/ a Manhattan view, longer stay",110506,Myung,Queens,Sunnyside,40.74559,-73.92313,Private room,79,30,28,2019-04-12,0.26,1,126
181,45910,Beautiful Queens Brownstone! - 5BR,204539,Mark,Queens,Ridgewood,40.70382,-73.89797,Entire home/apt,350,8,10,2019-05-12,0.11,5,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48858,36458668,"2beds Private Room Step to LGA, CitiFiled, Mid...",217463199,Marvy,Queens,Flushing,40.74387,-73.82556,Private room,68,3,0,NaN,NaN,4,362
48863,36469741,Comfortable & Big room with 2 beds!,274012871,Stefan,Queens,Long Island City,40.76726,-73.93936,Private room,93,2,0,NaN,NaN,2,14
48866,36472710,CozyHideAway Suite,274225617,Alberth,Queens,Briarwood,40.70786,-73.81448,Entire home/apt,58,1,0,NaN,NaN,1,159
48878,36479723,Room for rest,41326856,Jeerathinan,Queens,Elmhurst,40.74477,-73.87727,Private room,45,1,0,NaN,NaN,5,172
48889,36484363,QUIT PRIVATE HOUSE,107716952,Michael,Queens,Jamaica,40.69137,-73.80844,Private room,65,1,0,NaN,NaN,2,163

In [ ]:
df_1.groupby('neighbourhood')['price'].agg(['mean', 'var', 'max', 'min'])

                           mean            var    max  min
neighbourhood
Arverne              171.779221   37383.411141   1500   35
Astoria              117.187778  122428.811196  10000   25
Bay Terrace          142.000000    6816.400000    258   32
Bayside              157.948718  166106.470985   2600   30
Bayswater             87.470588    2330.889706    230   45
Belle Harbor         171.500000    8226.571429    350   85
Bellerose             99.357143    3093.016484    240   42
Breezy Point         213.333333    1008.333333    250  195
Briarwood            105.875000   18503.165909   1000   30
Cambria Heights       81.730769    2960.604615    250   31
College Point         88.000000    6445.555556    400   44
Corona                59.171875    2430.557292    359   23
Ditmars Steinway      95.029126    4214.112785    600   22
Douglaston            82.750000    2347.071429    178   40
East Elmhurst         81.183784    4369.487779    700   16
Edgemere              94.727273    4219.418182    200   40
Elmhurst              80.459916    3896.563005    443   15
Far Rockaway         165.862069   52575.980296    900   35
Flushing              93.514085   12417.177448   1500   15
Forest Hills         121.625000   44533.368881   2350   16
Fresh Meadows         99.500000    6394.451613    375   39
Glendale              90.796296    3230.882250    299   25
Hollis                88.642857    1483.016484    175   50
Holliswood           135.750000    5091.583333    239   79
Howard Beach         115.400000    4241.936842    250   40
Jackson Heights       80.897849    2150.470590    260   23
Jamaica               95.770563    8067.047130   1000   10
Jamaica Estates      182.947368   29006.052632    750   35
Jamaica Hills        132.125000   11304.696429    325   50
Kew Gardens           88.375000    2632.306452    219   35
Kew Gardens Hills    112.307692    6230.621538    399   40
Laurelton             95.333333    4355.529412    254   34
Little Neck           75.200000    2368.700000    149   32
Long Island City     127.465549   15529.503009   2000   30
Maspeth               83.645455    2223.607089    245   11
Middle Village       109.580645    3537.118280    265   28
Neponsit             274.666667    5625.333333    350  200
Ozone Park            85.274194    1705.415389    200   25
Queens Village        83.933333    2386.470056    320   25
Rego Park             83.877358    3659.003863    300   21
Richmond Hill         87.117021    3474.147449    300   28
Ridgewood             77.184397    2629.311889    375   20
Rockaway Beach       132.178571    6254.622078    545   49
Rosedale              76.694915    2963.939801    350   22
South Ozone Park      82.400000    4619.989744    400   29
Springfield Gardens   94.235294    2490.848739    300   40
St. Albans           100.828947    9489.903684    600   25
Sunnyside             84.865014    2727.746922    600   12
Whitestone           107.545455   13632.072727    400   35
Woodhaven             67.170455    1642.464864    250   10
Woodside              85.097872    5001.900636    500   28

In [ ]:
#문제55:
df['neighbourhood_group'].value_counts()

neighbourhood_group
Manhattan        21661
Brooklyn         20104
Queens            5666
Bronx             1091
Staten Island      373
Name: count, dtype: int64

In [ ]:
#문제55: 데이터중 neighbourhood_group 값에 따른 room_type 컬럼의 숫자를 구하고
# neighbourhood_group 값을 기준으로 각 값의 비율을 구하여라
df_1 = df[['neighbourhood_group', 'room_type']].groupby(['neighbourhood_group', 'room_type'], as_index=False).size()
df_1

   neighbourhood_group        room_type   size
0                Bronx  Entire home/apt    379
1                Bronx     Private room    652
2                Bronx      Shared room     60
3             Brooklyn  Entire home/apt   9559
4             Brooklyn     Private room  10132
5             Brooklyn      Shared room    413
6            Manhattan  Entire home/apt  13199
7            Manhattan     Private room   7982
8            Manhattan      Shared room    480
9               Queens  Entire home/apt   2096
10              Queens     Private room   3372
11              Queens      Shared room    198
12       Staten Island  Entire home/apt    176
13       Staten Island     Private room    188
14       Staten Island      Shared room      9

In [ ]:
lst = []

for x in df['neighbourhood_group'].value_counts()[df_1['neighbourhood_group'].unique()].values:
    for i in range(3):
        lst.append(x)

lst

[np.int64(1091),
 np.int64(1091),
 np.int64(1091),
 np.int64(20104),
 np.int64(20104),
 np.int64(20104),
 np.int64(21661),
 np.int64(21661),
 np.int64(21661),
 np.int64(5666),
 np.int64(5666),
 np.int64(5666),
 np.int64(373),
 np.int64(373),
 np.int64(373)]

In [ ]:
pd.Series(lst)

0      1091
1      1091
2      1091
3     20104
4     20104
5     20104
6     21661
7     21661
8     21661
9      5666
10     5666
11     5666
12      373
13      373
14      373
dtype: int64

In [ ]:
df_1.loc[:, 'ratio'] = df_1['size'] /pd.Series(lst)
df_1

   neighbourhood_group        room_type   size     ratio
0                Bronx  Entire home/apt    379  0.347388
1                Bronx     Private room    652  0.597617
2                Bronx      Shared room     60  0.054995
3             Brooklyn  Entire home/apt   9559  0.475478
4             Brooklyn     Private room  10132  0.503979
5             Brooklyn      Shared room    413  0.020543
6            Manhattan  Entire home/apt  13199  0.609344
7            Manhattan     Private room   7982  0.368496
8            Manhattan      Shared room    480  0.022160
9               Queens  Entire home/apt   2096  0.369926
10              Queens     Private room   3372  0.595129
11              Queens      Shared room    198  0.034945
12       Staten Island  Entire home/apt    176  0.471850
13       Staten Island     Private room    188  0.504021
14       Staten Island      Shared room      9  0.024129

In [ ]:
df_new = df[['neighbourhood_group', 'room_type']].groupby(['neighbourhood_group', 'room_type']).size()
df_new

neighbourhood_group  room_type
Bronx                Entire home/apt      379
                     Private room         652
                     Shared room           60
Brooklyn             Entire home/apt     9559
                     Private room       10132
                     Shared room          413
Manhattan            Entire home/apt    13199
                     Private room        7982
                     Shared room          480
Queens               Entire home/apt     2096
                     Private room        3372
                     Shared room          198
Staten Island        Entire home/apt      176
                     Private room         188
                     Shared room            9
dtype: int64

In [ ]:
ans = df_new.unstack()
ans

room_type            Entire home/apt  Private room  Shared room
neighbourhood_group
Bronx                            379           652           60
Brooklyn                        9559         10132          413
Manhattan                      13199          7982          480
Queens                          2096          3372          198
Staten Island                    176           188            9

In [ ]:
ans.loc[:, :] = (ans.values / ans.sum(axis=1).values.reshape(-1, 1))

/tmp/ipython-input-162497009.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.34738772 0.47547752 0.60934398 0.36992587 0.47184987]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ans.loc[:, :] = (ans.values / ans.sum(axis=1).values.reshape(-1, 1))
/tmp/ipython-input-162497009.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.59761687 0.50397931 0.36849638 0.59512884 0.50402145]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ans.loc[:, :] = (ans.values / ans.sum(axis=1).values.reshape(-1, 1))
/tmp/ipython-input-162497009.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.05499542 0.02054318 0.02215964 0.03494529 0.02412869]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ans.loc[:, :] = (ans.values / ans.sum(axis=1).values.reshape(-1, 1))

## 04.Apply, Map

In [ ]:
import pandas as pd    # 카드이용데이터
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/BankChurnersUp.csv', index_col=0)
df

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,772366833,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,3,2,3,4003.0,1851,2152.0,0.703,15476
10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,4,2,3,4277.0,2186,2091.0,0.804,8764
10124,716506083,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,5,3,4,5409.0,0,5409.0,0.819,10291
10125,717406983,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,4,3,3,5281.0,0,5281.0,0.535,8395
10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,6,2,4,10388.0,1961,8427.0,0.703,10294

In [ ]:
#문제56: 데이터를 로드하고 데이터 행과 열의 갯수를 출력하라
print(df.shape)
df.info()

(10127, 18)
<class 'pandas.core.frame.DataFrame'>
Index: 10127 entries, 0 to 10126
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CLIENTNUM                 10127 non-null  int64
 1   Attrition_Flag            10127 non-null  object
 2   Customer_Age              10127 non-null  int64
 3   Gender                    10127 non-null  object
 4   Dependent_count           10127 non-null  int64
 5   Education_Level           10127 non-null  object
 6   Marital_Status            10127 non-null  object
 7   Income_Category           10127 non-null  object
 8   Card_Category             10127 non-null  object
 9   Months_on_book            10127 non-null  int64
 10  Total_Relationship_Count  10127 non-null  int64
 11  Months_Inactive_12_mon    10127 non-null  int64
 12  Contacts_Count_12_mon     10127 non-null  int64
 13  Credit_Limit              10127 non-null  float64
 14  Total_Revolving_Bal       10127 non-null  int64
 15  Avg_Open_To_Buy           10127 non-null  float64
 16  Total_Amt_Chng_Q4_Q1      10127 non-null  float64
 17  Total_Trans_Amt           10127 non-null  int64
dtypes: float64(3), int64(9), object(6)
memory usage: 1.5+ MB

In [ ]:
#문제57: Income_Category의 카테고리를 map 함수를 이용하여 다음과 같이 변경하여
# newIncome 컬럼에 매핑하라 Unknown : N
# Less than $40K : a
# $40K - $60K : b
# $60K - $80K : c
# $80K - $120K : d
# $120K +’ : e
df['Income_Category'].unique()

array(['$60K - $80K', 'Less than $40K', '$80K - $120K', '$40K - $60K',
       '$120K +', 'Unknown'], dtype=object)

In [ ]:
dic = {
    'Less than $40K': 'a',
    '$40K - $60K': 'b',
    '$60K - $80K': 'c',
    '$80K - $120K': 'd',
    '$120K +': 'e',
    'Unknown': 'N'
}

In [ ]:
df['Income_Category'].map(dic).unique()

array(['c', 'a', 'd', 'b', 'e', 'N'], dtype=object)

array(['$60K - $80K', 'Less than $40K', '$80K - $120K', '$40K - $60K',
       '$120K +', 'Unknown'], dtype=object)

In [ ]:
df.loc[:, 'new_income']= df['Income_Category'].map(dic)
df

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,new_income
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,c
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,a
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,d
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,a
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,772366833,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,3,2,3,4003.0,1851,2152.0,0.703,15476,b
10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,4,2,3,4277.0,2186,2091.0,0.804,8764,b
10124,716506083,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,5,3,4,5409.0,0,5409.0,0.819,10291,a
10125,717406983,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,4,3,3,5281.0,0,5281.0,0.535,8395,b
10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,6,2,4,10388.0,1961,8427.0,0.703,10294,a

In [ ]:
#문제58: Income_Category의 카테고리를 apply 함수를 이용하여 다음과 같이 변경하여
# newIncome 컬럼에 매핑하라 Unknown : N
# Less than $40K : a
# $40K - $60K : b
# $60K - $80K : c
# $80K - $120K : d
# $120K +’ : e
def changeCategory(x):
    if x =='Unknown':
        return 'N'
    elif x =='Less than $40K':
        return 'a'
    elif x =='$40K - $60K':
        return 'b'
    elif x =='$60K - $80K':
        return 'c'
    elif x =='$80K - $120K':
        return 'd'
    elif x =='$120K +' :
        return 'e'

df['newIncome']  =df.Income_Category.apply(changeCategory)

Ans = df['newIncome']

In [ ]:
Ans

0        c
1        a
2        d
3        a
4        c
        ..
10122    b
10123    b
10124    a
10125    b
10126    a
Name: newIncome, Length: 10127, dtype: object